
STANDUP_GAINS_VALUE = 1.0
GAINS_ON_VALUE = 0.85
GAINS_ARMS_VALUE = 0.2
GAINS_OFF_VALUE = 0.0


STANDUP_STIFFNESSES = (STANDUP_GAINS_VALUE, STANDUP_GAINS_VALUE,
                       STANDUP_GAINS_VALUE, STANDUP_GAINS_VALUE,
                       STANDUP_GAINS_VALUE)

LOOSE_ARMS_STIFFNESSES = (GAINS_ON_VALUE, GAINS_ARMS_VALUE,
                          GAINS_ON_VALUE, GAINS_ON_VALUE, GAINS_ARMS_VALUE)

NORMAL_STIFFNESSES = (GAINS_ON_VALUE, GAINS_ON_VALUE,
                      GAINS_ON_VALUE, GAINS_ON_VALUE, GAINS_ON_VALUE)

NO_STIFFNESSES = (GAINS_OFF_VALUE, GAINS_OFF_VALUE,
                  GAINS_OFF_VALUE, GAINS_OFF_VALUE, GAINS_OFF_VALUE)

LEFT_FAR_KICK_STIFFNESS = (GAINS_ON_VALUE, GAINS_ARMS_VALUE,
                          GAINS_ON_VALUE, 0.4, GAINS_ARMS_VALUE)

