/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nbtool.gui;

/**
 *
 * @author pkoch
 */
public class ToplevelDisplay extends javax.swing.JFrame {

    /**
     * Creates new form TopLevelDisplay
     */
    public ToplevelDisplay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        TopLevelSplitPane = new javax.swing.JSplitPane();
        LeftTabbedPane = new javax.swing.JTabbedPane();
        UtilitiesTab = new javax.swing.JPanel();
        optionsPane = new javax.swing.JPanel();
        logLabel = new javax.swing.JLabel();
        logLevelComboBox = new javax.swing.JComboBox();
        hotkeysButton = new javax.swing.JCheckBox();
        utilitiesOutside = new javax.swing.JPanel();
        utilitiesScrollPane = new javax.swing.JScrollPane();
        ControlTab = new javax.swing.JPanel();
        fileSystemPanel = new javax.swing.JPanel();
        pathComboBox = new javax.swing.JComboBox();
        loadButton = new javax.swing.JButton();
        chooseButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        connectPanel = new javax.swing.JPanel();
        connectButton = new javax.swing.JButton();
        editableAddressBox = new javax.swing.JComboBox();
        presetAddressBox = new javax.swing.JComboBox();
        retainLogsCheckBox = new javax.swing.JCheckBox();
        controlPanel = new javax.swing.JPanel();
        controlScrollPane = new javax.swing.JScrollPane();
        LogsTab = new javax.swing.JPanel();
        sortAndSearchPanel = new javax.swing.JPanel();
        obLabel = new javax.swing.JLabel();
        sortByBox = new javax.swing.JComboBox();
        reversedCheckBox = new javax.swing.JCheckBox();
        showOnlyLabel = new javax.swing.JLabel();
        showOnlyField = new javax.swing.JTextField();
        logChooserScrollPane = new javax.swing.JScrollPane();
        logChooserTree = new javax.swing.JTree();
        DisplayPane = new javax.swing.JPanel();
        streamPanel = new javax.swing.JPanel();
        streamFor = new javax.swing.JTextField();
        streamingCheckbox = new javax.swing.JCheckBox();
        viewProfileBox = new javax.swing.JComboBox();
        mainLogDisplayPanel = new javax.swing.JPanel();
        footerPanel = new javax.swing.JPanel();
        memSpaceBar = new javax.swing.JProgressBar();
        memLabel = new javax.swing.JLabel();
        fsLabel = new javax.swing.JLabel();
        fsSpaceBar = new javax.swing.JProgressBar();
        eventLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("nbtool8-thingsup-yayayay");
        setBackground(javax.swing.UIManager.getDefaults().getColor("Button.disabledText"));

        TopLevelSplitPane.setBackground(new java.awt.Color(242, 242, 242));
        TopLevelSplitPane.setDividerLocation(500);
        TopLevelSplitPane.setDividerSize(5);
        TopLevelSplitPane.setForeground(new java.awt.Color(255, 255, 255));

        LeftTabbedPane.setBackground(new java.awt.Color(242, 242, 242));
        LeftTabbedPane.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.disabledText"));
        LeftTabbedPane.setOpaque(true);

        UtilitiesTab.setBackground(new java.awt.Color(242, 242, 242));

        optionsPane.setBackground(new java.awt.Color(242, 242, 242));
        optionsPane.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monospaced", 1, 13))); // NOI18N

        logLabel.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        logLabel.setText("tool printing level");

        logLevelComboBox.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        logLevelComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        logLevelComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logLevelComboBoxActionPerformed(evt);
            }
        });

        hotkeysButton.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        hotkeysButton.setText("show hotkeys on relaunch");
        hotkeysButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout optionsPaneLayout = new javax.swing.GroupLayout(optionsPane);
        optionsPane.setLayout(optionsPaneLayout);
        optionsPaneLayout.setHorizontalGroup(
            optionsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionsPaneLayout.createSequentialGroup()
                        .addComponent(logLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logLevelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionsPaneLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(hotkeysButton)))
                .addContainerGap())
        );
        optionsPaneLayout.setVerticalGroup(
            optionsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logLevelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hotkeysButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        utilitiesOutside.setBackground(new java.awt.Color(242, 242, 242));
        utilitiesOutside.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "utilities", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monospaced", 1, 13))); // NOI18N

        utilitiesScrollPane.setBorder(null);

        javax.swing.GroupLayout utilitiesOutsideLayout = new javax.swing.GroupLayout(utilitiesOutside);
        utilitiesOutside.setLayout(utilitiesOutsideLayout);
        utilitiesOutsideLayout.setHorizontalGroup(
            utilitiesOutsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(utilitiesScrollPane)
        );
        utilitiesOutsideLayout.setVerticalGroup(
            utilitiesOutsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(utilitiesScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout UtilitiesTabLayout = new javax.swing.GroupLayout(UtilitiesTab);
        UtilitiesTab.setLayout(UtilitiesTabLayout);
        UtilitiesTabLayout.setHorizontalGroup(
            UtilitiesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(optionsPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(utilitiesOutside, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        UtilitiesTabLayout.setVerticalGroup(
            UtilitiesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UtilitiesTabLayout.createSequentialGroup()
                .addComponent(optionsPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(utilitiesOutside, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LeftTabbedPane.addTab("utilities", UtilitiesTab);

        ControlTab.setBackground(new java.awt.Color(242, 242, 242));

        fileSystemPanel.setBackground(new java.awt.Color(242, 242, 242));
        fileSystemPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "load from filesystem", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monospaced", 1, 13))); // NOI18N

        pathComboBox.setEditable(true);
        pathComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pathComboBox.setToolTipText("");

        loadButton.setText("load dir");

        chooseButton.setText("choose dir (GUI)");

        clearButton.setText("clear path");

        javax.swing.GroupLayout fileSystemPanelLayout = new javax.swing.GroupLayout(fileSystemPanel);
        fileSystemPanel.setLayout(fileSystemPanelLayout);
        fileSystemPanelLayout.setHorizontalGroup(
            fileSystemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileSystemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pathComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(fileSystemPanelLayout.createSequentialGroup()
                .addComponent(loadButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chooseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        fileSystemPanelLayout.setVerticalGroup(
            fileSystemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileSystemPanelLayout.createSequentialGroup()
                .addComponent(pathComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fileSystemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadButton)
                    .addComponent(chooseButton)
                    .addComponent(clearButton)))
        );

        connectPanel.setBackground(new java.awt.Color(242, 242, 242));
        connectPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "connect to robot", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monospaced", 1, 13))); // NOI18N

        connectButton.setText("connect");

        editableAddressBox.setEditable(true);
        editableAddressBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        presetAddressBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        retainLogsCheckBox.setText("retain streamed logs");
        retainLogsCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retainLogsCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout connectPanelLayout = new javax.swing.GroupLayout(connectPanel);
        connectPanel.setLayout(connectPanelLayout);
        connectPanelLayout.setHorizontalGroup(
            connectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, connectPanelLayout.createSequentialGroup()
                .addGroup(connectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(retainLogsCheckBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(connectPanelLayout.createSequentialGroup()
                        .addComponent(connectButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editableAddressBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(presetAddressBox, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        connectPanelLayout.setVerticalGroup(
            connectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(connectPanelLayout.createSequentialGroup()
                .addGroup(connectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(connectButton)
                    .addComponent(editableAddressBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(presetAddressBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(retainLogsCheckBox)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        controlPanel.setBackground(new java.awt.Color(242, 242, 242));
        controlPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "control robot", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monospaced", 0, 13))); // NOI18N

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(controlScrollPane)
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(controlScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ControlTabLayout = new javax.swing.GroupLayout(ControlTab);
        ControlTab.setLayout(ControlTabLayout);
        ControlTabLayout.setHorizontalGroup(
            ControlTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fileSystemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(connectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(controlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ControlTabLayout.setVerticalGroup(
            ControlTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlTabLayout.createSequentialGroup()
                .addComponent(fileSystemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(connectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(controlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LeftTabbedPane.addTab("control", ControlTab);

        sortAndSearchPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "sort and search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monospaced", 1, 13))); // NOI18N

        obLabel.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        obLabel.setText("order by:");

        sortByBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        sortByBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortByBoxActionPerformed(evt);
            }
        });

        reversedCheckBox.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        reversedCheckBox.setText("(reversed)");
        reversedCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        showOnlyLabel.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        showOnlyLabel.setText("show only:");

        showOnlyField.setText("jTextField1");

        javax.swing.GroupLayout sortAndSearchPanelLayout = new javax.swing.GroupLayout(sortAndSearchPanel);
        sortAndSearchPanel.setLayout(sortAndSearchPanelLayout);
        sortAndSearchPanelLayout.setHorizontalGroup(
            sortAndSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sortAndSearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sortAndSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sortAndSearchPanelLayout.createSequentialGroup()
                        .addComponent(obLabel)
                        .addGap(18, 18, 18)
                        .addComponent(sortByBox, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(reversedCheckBox))
                    .addGroup(sortAndSearchPanelLayout.createSequentialGroup()
                        .addComponent(showOnlyLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showOnlyField)))
                .addContainerGap())
        );
        sortAndSearchPanelLayout.setVerticalGroup(
            sortAndSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sortAndSearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sortAndSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(obLabel)
                    .addComponent(sortByBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reversedCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sortAndSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showOnlyLabel)
                    .addComponent(showOnlyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        logChooserScrollPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        logChooserScrollPane.setViewportView(logChooserTree);

        javax.swing.GroupLayout LogsTabLayout = new javax.swing.GroupLayout(LogsTab);
        LogsTab.setLayout(LogsTabLayout);
        LogsTabLayout.setHorizontalGroup(
            LogsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sortAndSearchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logChooserScrollPane)
        );
        LogsTabLayout.setVerticalGroup(
            LogsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogsTabLayout.createSequentialGroup()
                .addComponent(sortAndSearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logChooserScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE))
        );

        LeftTabbedPane.addTab("logs", LogsTab);

        TopLevelSplitPane.setLeftComponent(LeftTabbedPane);

        DisplayPane.setBackground(new java.awt.Color(242, 242, 242));
        DisplayPane.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.disabledText"));

        streamPanel.setBackground(new java.awt.Color(255, 255, 255));
        streamPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        streamFor.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        streamFor.setText("tripoint");

        streamingCheckbox.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        streamingCheckbox.setText("stream w/");
        streamingCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streamingCheckboxActionPerformed(evt);
            }
        });

        viewProfileBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout streamPanelLayout = new javax.swing.GroupLayout(streamPanel);
        streamPanel.setLayout(streamPanelLayout);
        streamPanelLayout.setHorizontalGroup(
            streamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(streamPanelLayout.createSequentialGroup()
                .addComponent(streamingCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(streamFor, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewProfileBox, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        streamPanelLayout.setVerticalGroup(
            streamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(streamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(streamingCheckbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(streamFor)
                .addComponent(viewProfileBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainLogDisplayPanel.setBackground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout mainLogDisplayPanelLayout = new javax.swing.GroupLayout(mainLogDisplayPanel);
        mainLogDisplayPanel.setLayout(mainLogDisplayPanelLayout);
        mainLogDisplayPanelLayout.setHorizontalGroup(
            mainLogDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mainLogDisplayPanelLayout.setVerticalGroup(
            mainLogDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout DisplayPaneLayout = new javax.swing.GroupLayout(DisplayPane);
        DisplayPane.setLayout(DisplayPaneLayout);
        DisplayPaneLayout.setHorizontalGroup(
            DisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(streamPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainLogDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DisplayPaneLayout.setVerticalGroup(
            DisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DisplayPaneLayout.createSequentialGroup()
                .addComponent(mainLogDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(streamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        TopLevelSplitPane.setRightComponent(DisplayPane);

        footerPanel.setBackground(new java.awt.Color(204, 204, 204));

        memLabel.setText("MEM");

        fsLabel.setText("FS");

        eventLabel.setText("jLabel3");

        javax.swing.GroupLayout footerPanelLayout = new javax.swing.GroupLayout(footerPanel);
        footerPanel.setLayout(footerPanelLayout);
        footerPanelLayout.setHorizontalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(memLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(memSpaceBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fsSpaceBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eventLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        footerPanelLayout.setVerticalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eventLabel)
                    .addComponent(fsSpaceBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fsLabel)
                    .addGroup(footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(memSpaceBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(memLabel))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TopLevelSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 805, Short.MAX_VALUE)
            .addComponent(footerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TopLevelSplitPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(footerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>                        

    private void streamingCheckboxActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void sortByBoxActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void logLevelComboBoxActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void retainLogsCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  


    // Variables declaration - do not modify                     
    public javax.swing.JPanel ControlTab;
    public javax.swing.JPanel DisplayPane;
    public javax.swing.JTabbedPane LeftTabbedPane;
    public javax.swing.JPanel LogsTab;
    public javax.swing.JSplitPane TopLevelSplitPane;
    public javax.swing.JPanel UtilitiesTab;
    public javax.swing.JButton chooseButton;
    public javax.swing.JButton clearButton;
    public javax.swing.JButton connectButton;
    public javax.swing.JPanel connectPanel;
    public javax.swing.JPanel controlPanel;
    public javax.swing.JScrollPane controlScrollPane;
    public javax.swing.JComboBox editableAddressBox;
    public javax.swing.JLabel eventLabel;
    public javax.swing.JPanel fileSystemPanel;
    public javax.swing.JPanel footerPanel;
    public javax.swing.JLabel fsLabel;
    public javax.swing.JProgressBar fsSpaceBar;
    public javax.swing.JCheckBox hotkeysButton;
    public javax.swing.JButton loadButton;
    public javax.swing.JScrollPane logChooserScrollPane;
    public javax.swing.JTree logChooserTree;
    public javax.swing.JLabel logLabel;
    public javax.swing.JComboBox logLevelComboBox;
    public javax.swing.JPanel mainLogDisplayPanel;
    public javax.swing.JLabel memLabel;
    public javax.swing.JProgressBar memSpaceBar;
    public javax.swing.JLabel obLabel;
    public javax.swing.JPanel optionsPane;
    public javax.swing.JComboBox pathComboBox;
    public javax.swing.JComboBox presetAddressBox;
    public javax.swing.JCheckBox retainLogsCheckBox;
    public javax.swing.JCheckBox reversedCheckBox;
    public javax.swing.JTextField showOnlyField;
    public javax.swing.JLabel showOnlyLabel;
    public javax.swing.JPanel sortAndSearchPanel;
    public javax.swing.JComboBox sortByBox;
    public javax.swing.JTextField streamFor;
    public javax.swing.JPanel streamPanel;
    public javax.swing.JCheckBox streamingCheckbox;
    public javax.swing.JPanel utilitiesOutside;
    public javax.swing.JScrollPane utilitiesScrollPane;
    public javax.swing.JComboBox viewProfileBox;
    // End of variables declaration                   
}
