from ..navigator import BrunswickSpeeds as speeds

# Component Switches
USE_DRIBBLE = False

# Transitions' Constants
# Ball on and off frame thresholds
BALL_ON_THRESH = 2
BALL_OFF_THRESH = 30
BALL_OFF_KICK_THRESH = 80

# Should position for kick
BALL_PFK_BEARING_THRESH = 15
BALL_PFK_LEFT_Y = 16.0
BALL_PFK_RIGHT_Y = -BALL_PFK_LEFT_Y
BALL_PFK_MAX_X = 75
BALL_PFK_MIN_X = 16

# Should spin to kick
SHOULD_SPIN_TO_KICK_X = 9.5
SHOULD_SPIN_TO_KICK_Y = 7
SHOULD_SPIN_TO_KICK_DIST = 40

# Should dribble should and should stop dribbling
SHOULD_DRIBBLE_X = BALL_PFK_MAX_X
SHOULD_DRIBBLE_Y = BALL_PFK_LEFT_Y
SHOULD_DRIBBLE_BEARING = 30.0
STOP_DRIBBLE_X = SHOULD_DRIBBLE_X + 20
STOP_DRIBBLE_Y = SHOULD_DRIBBLE_Y + 20
STOP_DRIBBLE_BEARING = 40.0

# States' constants
# turnToBall
FIND_BALL_SPIN_SPEED = speeds.MAX_SPIN_MAGNITUDE
BALL_SPIN_SPEED = speeds.MAX_SPIN_MAGNITUDE

# shouldKick()
SHOULD_STOP_DIST = 60
SHOULD_STOP_Y = BALL_PFK_LEFT_Y
SHOULD_KICK_CLOSE_X = 10
SHOULD_KICK_FAR_X = 16
SHOULD_KICK_Y = 9

CHASE_AFTER_KICK_FRAMES = 100

# find ball
WALK_FIND_BALL_FRAMES_THRESH = 720
SCAN_FIND_BEARING_THRESH = 50

STOP_PENALTY_DRIBBLE_COUNT = 120
