from ..navigator import BrunswickSpeeds as speeds

USE_SQUAT_DEFENDER = False

BALL_SPIN_POSITION_THRESH = 10
BALL_SPIN_BUFFER = 10
BALL_OFF_SPIN_TIME = 30

RELOC_UNCERT_XY_THRESH = 100
RELOC_UNCERT_THETA_THRESH = 40
WELL_LOCED_UNCERT_XY = 30
WELL_LOCED_UNCERT_THRESH = 25

RELOC_SPIN_FRAME_THRESH = 200
SHOULD_RELOC_FRAME_THRESH = 6

RELOC_SPIN_SPEED = speeds.MAX_SPIN_MAGNITUDE
RELOC_X_SPEED = 0.5

AT_POSITION_KICK_DIST = 25
NOT_AT_POSITION_FRAMES_THRESH = 5
CHANGE_OMNI_THRESH = 0
GOTO_DEST_EPSILON = 10.


#Leaving the field
LOOK_FORWARD_THRESH = 5
CLOSE_TO_FIELD_EDGE = 100
SPIN_AROUND_RIGHT = 180
SPIN_AROUND_LEFT = -180
