from ..navigator import BrunswickSpeeds as speeds

RELOC_SPIN_FRAME_THRESH = 200

RELOC_SPIN_SPEED = speeds.MAX_SPIN_MAGNITUDE
RELOC_X_SPEED = 0.5

AT_POSITION_KICK_DIST = 25

#Leaving the field
LOOK_FORWARD_THRESH = 5
CLOSE_TO_FIELD_EDGE = 100
SPIN_AROUND_RIGHT = 180
SPIN_AROUND_LEFT = -180
