#
# All of the constants used for the Goalie
# are kept here.
#

import noggin_constants as constants
from math import atan2, degrees

RIGHT = 0
LEFT = 1
UNKNOWN = 2

CENTER_POSE = 0
RIGHT_POSE = 1
LEFT_POSE = 2

EXPECTED_CORNER_DIST_FROM_CENTER = 105.0
EXPECTED_LEFT_CORNER_BEARING_FROM_CENTER = 63.0
EXPECTED_RIGHT_CORNER_BEARING_FROM_CENTER = -63.0

CORNER_DISTANCE_THRESH = 10.0
CORNER_BEARING_THRESH = 10.0

GOALIE_OFFSET = 0.0
BUFFER_THRESH = 5

OVERZEALOUS_ODO = 2.0
STOP_NAV_THRESH = 5.0

BALL_ON_SAFE_THRESH = 50
BALL_SAFE_DISTANCE_THRESH = 150.0

# -----------------------------------
# Crazy new vision system constants:
EXPECTED_SIDE_LINE_R = 87.0
EXPECTED_FRONT_LINE_R = 50.0

EXPECTED_LEFT_LINE_T = 90.0
EXPECTED_RIGHT_LINE_T = 270.0
EXPECTED_FRONT_LINE_T = 5.0
EXPECTED_FRONT_LINE_T_2 = 355.0

T_THRESH = 15.0
R_THRESH = 15.0

MEM_THRESH = 15

CLEARIT_DIST = 140.0

CENTER_POSITION = 1
RIGHT_POSITION = 2
LEFT_POSITION = 3
NOT_IN_POSITION = 0

# SAVING
SAVE_X_VEL = -9.0
SAVE_DIST = 150.0