#
# All of the constants used for the Goalie
# are kept here.
#

import noggin_constants as constants
from math import atan2, degrees

RIGHT = 0
LEFT = 1
UNKNOWN = 2

CENTER_POSE = 0
RIGHT_POSE = 1
LEFT_POSE = 2

EXPECTED_CORNER_DIST_FROM_CENTER = 105.0
EXPECTED_LEFT_CORNER_BEARING_FROM_CENTER = 63.0
EXPECTED_RIGHT_CORNER_BEARING_FROM_CENTER = -63.0

CORNER_DISTANCE_THRESH = 10.0
CORNER_BEARING_THRESH = 20.0

GOALIE_OFFSET = 0.0
BUFFER_THRESH = 10

OVERZEALOUS_ODO = 2.0
STOP_NAV_THRESH = 5.0

BALL_ON_SAFE_THRESH = 50
BALL_SAFE_DISTANCE_THRESH = 150.0
