import noggin_constants as NogginConstants
from objects import Location

KICK_STRAIGHT_BEARING_THRESH = 20

(LEFT_FOOT,
 RIGHT_FOOT,
 MID_LEFT,
 MID_RIGHT,
 INCORRECT_POS ) = range(5)

# Kick objectives
NUM_OBJECTIVES = 6
(OBJECTIVE_CLEAR,
 OBJECTIVE_CENTER,
 OBJECTIVE_SHOOT_CLOSE,
 OBJECTIVE_SHOOT_FAR,
 OBJECTIVE_KICKOFF,
 OBJECTIVE_UNCLEAR) = range(NUM_OBJECTIVES)
