package nbtool.gui.logviews.sound2;

import nbtool.data.Log;
import nbtool.gui.logviews.misc.ViewParent;

public class CorrelationView extends ViewParent {
	
	private static final int TARGET_F = 400;
	
	public CorrelationView() {
		super();
		initComponents();
		
		magSlider.setEnabled(false);
		diffSlider.setEnabled(false);
	}
	
	private int percentForRange(double min, double max, double val) {
		assert( min < max && val >= min && val <= max);
		double fraction = (val - min) / (max - min);
		return (int) (100 * fraction);
	}

	@Override
	public void setLog(Log newlog) {
		
		int srate = newlog.sexprForContentItem(0)
				.firstValueOf("rate").valueAsInt();
		assert(srate > (TARGET_F * 2));
		
		ShortBuffer buf = new ShortBuffer();
		buf.parse(newlog);
		Correlator cor = new Correlator(buf.channels,
				srate / TARGET_F, 1.0d);
		
		details1.setText(String.format("srate=%d target_f=%d", 
				srate, TARGET_F));
		details2.setText(String.format("frames=%d chnls=%d", 
				buf.frames, buf.channels));
		
		for (int j = 0; j < buf.channels; ++j) {
			for (int i = 0; i < buf.frames; ++i) {
				cor.correlate(j, i, buf.get(j, i));
			}
		}
		
		double lo = cor.offset(0);
		double ro = cor.offset(1);
		
		leftLabel.setText("left " + lo);
		leftBar.setValue(
				percentForRange(-Math.PI, Math.PI, lo)
				);
		
		rightLabel.setText("right " + ro);
		rightBar.setValue(
				percentForRange(-Math.PI, Math.PI, ro)
				);
		
		double diff = lo - ro;
		diffLabel.setText("difference " + diff);
		diffSlider.setValue(
				percentForRange(-2 *Math.PI, 2 * Math.PI, diff)
				);
		
		double lm = cor.magnitude(0);
		double rm = cor.magnitude(1);
		magLabel.setText(String.format("magnitude: (%s, %s)",
				String.format("%6.3e", lm), String.format("%6.3e", rm)));
		int ms = (int) (100 * (lm / (lm + rm)));
		magSlider.setValue(ms);
	}
	
	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        leftBar = new javax.swing.JProgressBar();
        rightBar = new javax.swing.JProgressBar();
        leftLabel = new javax.swing.JLabel();
        rightLabel = new javax.swing.JLabel();
        diffLabel = new javax.swing.JLabel();
        magLabel = new javax.swing.JLabel();
        DMIN_LABEL = new javax.swing.JLabel();
        DMAX_LABEL = new javax.swing.JLabel();
        magSlider = new javax.swing.JSlider();
        diffSlider = new javax.swing.JSlider();
        details1 = new javax.swing.JLabel();
        details2 = new javax.swing.JLabel();

        leftLabel.setText("left");

        rightLabel.setText("right");

        diffLabel.setText("difference");

        magLabel.setText("magnitude:");

        DMIN_LABEL.setText("-2PI");

        DMAX_LABEL.setText("2PI");

        magSlider.setToolTipText("");
        magSlider.setFocusable(false);

        diffSlider.setMinimum(-100);
        diffSlider.setFocusable(false);

        details1.setText("jLabel1");

        details2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(magLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(magSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(diffSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(DMIN_LABEL)
                        .addGap(206, 206, 206)
                        .addComponent(diffLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 320, Short.MAX_VALUE)
                        .addComponent(DMAX_LABEL))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rightLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(leftLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(leftBar, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                            .addComponent(rightBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(details1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(details2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(details1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(details2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(leftBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leftLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rightBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rightLabel))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diffLabel)
                    .addComponent(DMIN_LABEL)
                    .addComponent(DMAX_LABEL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(diffSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(magLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(magSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JLabel DMAX_LABEL;
    private javax.swing.JLabel DMIN_LABEL;
    private javax.swing.JLabel details1;
    private javax.swing.JLabel details2;
    private javax.swing.JLabel diffLabel;
    private javax.swing.JSlider diffSlider;
    private javax.swing.JProgressBar leftBar;
    private javax.swing.JLabel leftLabel;
    private javax.swing.JLabel magLabel;
    private javax.swing.JSlider magSlider;
    private javax.swing.JProgressBar rightBar;
    private javax.swing.JLabel rightLabel;
    // End of variables declaration 
}
