####### LED DEFINITIONS #############
LED_OFF = 0
LED_ON = 1

#GROUPS
LEFT_FOOT_LED   = "LeftFootLeds"
RIGHT_FOOT_LED  = "RightFootLeds"
CHEST_LED       = "ChestLeds"
LEFT_EYE_LED    = "LeftFaceLeds"
RIGHT_EYE_LED   = "RightFaceLeds"
FACE_LED        = "FaceLeds"
EAR_LED         = "EarLeds"

#COLORS
RED   = 0xFF0000
GREEN = 0x00FF00
BLUE  = 0x0000FF
YELLOW= 0xFFFF00
WHITE = 0xFFFFFF
OFF   = 0x000000
NOW = 0.0



###### GC LEDS ##########
###### KICKOFF ##########
HAVE_KICKOFF_LEDS  = ((RIGHT_FOOT_LED, WHITE, NOW),)
NO_KICKOFF_LEDS    = ((RIGHT_FOOT_LED, OFF, NOW),)

###### TEAM COLOR ##########
TEAM_BLUE_LEDS = ((LEFT_FOOT_LED, BLUE, NOW),)
TEAM_RED_LEDS = ((LEFT_FOOT_LED, RED, NOW),)

###### STATES ###########
STATE_INITIAL_LEDS =  ((CHEST_LED, OFF,    NOW),)
STATE_READY_LEDS =    ((CHEST_LED, BLUE,   NOW),)
STATE_SET_LEDS =      ((CHEST_LED, YELLOW, NOW),)
STATE_PLAYING_LEDS =  ((CHEST_LED, GREEN,  NOW),)
STATE_PENALIZED_LEDS =((CHEST_LED, RED,    NOW),)
STATE_FINISHED_LEDS = ((CHEST_LED, OFF,    NOW),)

##### Brain ######
#### Ball #######
BALL_ON_LEDS = ((FACE_LED, RED,    NOW),)
BALL_OFF_LEDS = ((FACE_LED, BLUE,    NOW),)


#### GOAL ######
GOAL_ON_LEDS = ((EAR_LED, BLUE,    NOW),)
GOAL_OFF_LEDS = ((EAR_LED, OFF,    NOW),)
