GOTO_FORWARD_SPEED = 6
GOTO_BACKWARD_SPEED = -4
GOTO_STRAFE_SPEED = 4
GOTO_SPIN_SPEED = 20
GOTO_SPIN_STRAFE = 0
GOTO_SURE_THRESH = 5

CHANGE_SPIN_DIR_THRESH = 3

# orbitPoint values
ORBIT_SPIN_SPEED = -20
ORBIT_STRAFE_SPEED = 8

ORBIT_LEFT = -1
ORBIT_RIGHT = 1
ORBIT_SMALL_ANGLE = 35
ORBIT_SMALL_GAIN = .5
ORBIT_MID_GAIN = .8
ORBIT_LARGE_ANGLE = 90
ORBIT_LARGE_GAIN = 1

FRAME_RATE = 19                 # Rough estimate. fps
