#navstates.py
GOTO_FORWARD_SPEED = 6
GOTO_BACKWARD_SPEED = -4
GOTO_STRAFE_SPEED = 6
GOTO_SPIN_SPEED = 30
GOTO_STRAIGHT_SPIN_SPEED = 20
GOTO_SPIN_STRAFE = 0
GOTO_SURE_THRESH = 5

OMNI_GOTO_FORWARD_SPEED = 6
OMNI_GOTO_STRAFE_SPEED = 6

CHANGE_SPIN_DIR_THRESH = 3

# orbitPoint values
ORBIT_SPIN_SPEED = -20
ORBIT_STRAFE_SPEED = 8

ORBIT_LEFT = -1
ORBIT_RIGHT = 1
ORBIT_SMALL_ANGLE = 35
ORBIT_SMALL_GAIN = .5
ORBIT_MID_GAIN = 1
ORBIT_LARGE_ANGLE = 90
ORBIT_LARGE_GAIN = 1

#navigator.py
LOC_IS_ACTIVE_H  = 400
CLOSE_ENOUGH_XY = 25.0
CLOSER_XY = 5.0
CLOSE_ENOUGH_H = 5.0
ALMOST_CLOSE_ENOUGH_H = 30.0

HEADING_NEAR_THRESH = 10.
HEADING_MEDIUM_THRESH = 30.

HEADING_NEAR_SCALE = 0.3
HEADING_MEDIUM_SCALE = 0.6
HEADING_FAR_SCALE = 1.0
SPIN_EPSILON = 2.0
FORWARD_EPSILON = 0.3
STRAFE_EPSILON = 0.5

POSITION_NEAR_THRESH = CLOSER_XY
POSITION_MEDIUM_THRESH = CLOSE_ENOUGH_XY
POSITION_NEAR_SCALE = 0
POSITION_MEDIUM_SCALE = 0.6
POSITION_FAR_SCALE = 1.0

FRAME_RATE = 20                 # Rough estimate. fps

