TRACKING = 'tracking'

LOC_PANS = 'locPans'

PAN_LEFT_ONCE = 'panLeftOnce'

MAX_PAN_SPEED = 100              # deg/sec

TRACKER_FRAMES_ON_TRACK_THRESH = 1
TRACKER_FRAMES_OFF_REFIND_THRESH = 10
ACTIVE_LOC_STARE_THRESH = 30
ACTIVE_LOC_OFF_REFIND_THRESH = 40
