// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Vision.proto

package messages;

public final class _File_Vision {
  private _File_Vision() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_HoughLine_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_HoughLine_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_FieldLine_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_FieldLine_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_Corner_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_Corner_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_CenterCircle_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_CenterCircle_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_Vision_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_Vision_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_VBall_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_VBall_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_FilteredBall_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_FilteredBall_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_SharedBall_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_SharedBall_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Vision.proto\022\010messages\";\n\tHoughLine\022\t\n" +
      "\001r\030\001 \001(\002\022\t\n\001t\030\002 \001(\002\022\013\n\003ep0\030\003 \001(\002\022\013\n\003ep1\030" +
      "\004 \001(\002\"\241\001\n\tFieldLine\022\"\n\005inner\030\001 \001(\0132\023.mes" +
      "sages.HoughLine\022\"\n\005outer\030\002 \001(\0132\023.message" +
      "s.HoughLine\022\n\n\002id\030\003 \001(\005\022\026\n\016correspondenc" +
      "e\030\004 \001(\005\022\014\n\004prob\030\005 \001(\002\022\r\n\005index\030\006 \001(\005\022\013\n\003" +
      "wz0\030\007 \001(\002\"n\n\006Corner\022\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(" +
      "\002\022\n\n\002id\030\003 \001(\005\022\026\n\016correspondence\030\004 \001(\005\022\014\n" +
      "\004prob\030\005 \001(\002\022\r\n\005line1\030\006 \001(\005\022\r\n\005line2\030\007 \001(" +
      "\005\">\n\014CenterCircle\022\n\n\002on\030\001 \001(\010\022\t\n\001x\030\002 \001(\002",
      "\022\t\n\001y\030\003 \001(\002\022\014\n\004prob\030\004 \001(\002\"\224\001\n\006Vision\022!\n\004" +
      "line\030\001 \003(\0132\023.messages.FieldLine\022 \n\006corne" +
      "r\030\002 \003(\0132\020.messages.Corner\022&\n\006circle\030\003 \001(" +
      "\0132\026.messages.CenterCircle\022\035\n\004ball\030\004 \001(\0132" +
      "\017.messages.VBall\"\254\002\n\005VBall\022\020\n\010distance\030\001" +
      " \001(\001\022\017\n\007bearing\030\002 \001(\001\022\023\n\013angle_x_deg\030\003 \001" +
      "(\001\022\023\n\013angle_y_deg\030\004 \001(\001\022\022\n\nbearing_sd\030\005 " +
      "\001(\001\022\020\n\010inTopCam\030\006 \001(\010\022\016\n\006radius\030\007 \001(\001\022\022\n" +
      "\nconfidence\030\010 \001(\001\022\n\n\002on\030\t \001(\010\022\021\n\tframes_" +
      "on\030\n \001(\021\022\022\n\nframes_off\030\013 \001(\021\022\026\n\016rel_x_va",
      "riance\030\014 \001(\001\022\026\n\016rel_y_variance\030\r \001(\001\022\023\n\013" +
      "bearing_deg\030\016 \001(\001\022\t\n\001x\030\017 \001(\021\022\t\n\001y\030\020 \001(\021\"" +
      "\315\004\n\014FilteredBall\022\034\n\003vis\030\001 \001(\0132\017.messages" +
      ".VBall\022\020\n\010distance\030\002 \001(\002\022\017\n\007bearing\030\003 \001(" +
      "\002\022\r\n\005rel_x\030\004 \001(\002\022\r\n\005rel_y\030\005 \001(\002\022\r\n\005vel_x" +
      "\030\006 \001(\002\022\r\n\005vel_y\030\007 \001(\002\022\021\n\tvar_rel_x\030\010 \001(\002" +
      "\022\021\n\tvar_rel_y\030\t \001(\002\022\021\n\tvar_vel_x\030\n \001(\002\022\021" +
      "\n\tvar_vel_y\030\013 \001(\002\022\025\n\ris_stationary\030\014 \001(\010" +
      "\022\023\n\013bearing_deg\030\r \001(\002\022\t\n\001x\030\016 \001(\002\022\t\n\001y\030\017 " +
      "\001(\002\022\022\n\nrel_x_dest\030\020 \001(\002\022\022\n\nrel_y_dest\030\021 ",
      "\001(\002\022\r\n\005speed\030\022 \001(\002\022\034\n\024rel_y_intersect_de" +
      "st\030\023 \001(\002\022\022\n\nstat_rel_x\030\024 \001(\002\022\022\n\nstat_rel" +
      "_y\030\025 \001(\002\022\025\n\rstat_distance\030\026 \001(\002\022\024\n\014stat_" +
      "bearing\030\027 \001(\002\022\021\n\tmov_rel_x\030\030 \001(\002\022\021\n\tmov_" +
      "rel_y\030\031 \001(\002\022\024\n\014mov_distance\030\032 \001(\002\022\023\n\013mov" +
      "_bearing\030\033 \001(\002\022\021\n\tmov_vel_x\030\034 \001(\002\022\021\n\tmov" +
      "_vel_y\030\035 \001(\002\022\021\n\tmov_speed\030\036 \001(\002\"H\n\nShare" +
      "dBall\022\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\022\017\n\007ball_on\030\003" +
      " \001(\010\022\023\n\013reliability\030\004 \001(\005B\020B\014_File_Visio" +
      "nP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_messages_HoughLine_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_messages_HoughLine_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_messages_HoughLine_descriptor,
        new java.lang.String[] { "R", "T", "Ep0", "Ep1", });
    internal_static_messages_FieldLine_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_messages_FieldLine_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_messages_FieldLine_descriptor,
        new java.lang.String[] { "Inner", "Outer", "Id", "Correspondence", "Prob", "Index", "Wz0", });
    internal_static_messages_Corner_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_messages_Corner_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_messages_Corner_descriptor,
        new java.lang.String[] { "X", "Y", "Id", "Correspondence", "Prob", "Line1", "Line2", });
    internal_static_messages_CenterCircle_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_messages_CenterCircle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_messages_CenterCircle_descriptor,
        new java.lang.String[] { "On", "X", "Y", "Prob", });
    internal_static_messages_Vision_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_messages_Vision_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_messages_Vision_descriptor,
        new java.lang.String[] { "Line", "Corner", "Circle", "Ball", });
    internal_static_messages_VBall_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_messages_VBall_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_messages_VBall_descriptor,
        new java.lang.String[] { "Distance", "Bearing", "AngleXDeg", "AngleYDeg", "BearingSd", "InTopCam", "Radius", "Confidence", "On", "FramesOn", "FramesOff", "RelXVariance", "RelYVariance", "BearingDeg", "X", "Y", });
    internal_static_messages_FilteredBall_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_messages_FilteredBall_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_messages_FilteredBall_descriptor,
        new java.lang.String[] { "Vis", "Distance", "Bearing", "RelX", "RelY", "VelX", "VelY", "VarRelX", "VarRelY", "VarVelX", "VarVelY", "IsStationary", "BearingDeg", "X", "Y", "RelXDest", "RelYDest", "Speed", "RelYIntersectDest", "StatRelX", "StatRelY", "StatDistance", "StatBearing", "MovRelX", "MovRelY", "MovDistance", "MovBearing", "MovVelX", "MovVelY", "MovSpeed", });
    internal_static_messages_SharedBall_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_messages_SharedBall_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_messages_SharedBall_descriptor,
        new java.lang.String[] { "X", "Y", "BallOn", "Reliability", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
