// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TeamPacket.proto

package messages;

public final class _File_TeamPacket {
  private _File_TeamPacket() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_TeamPacket_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_TeamPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020TeamPacket.proto\022\010messages\032\020WorldModel" +
      ".proto\"\233\001\n\nTeamPacket\022\016\n\006header\030\001 \001(\t\022\023\n" +
      "\013team_number\030\002 \001(\005\022\025\n\rplayer_number\030\003 \001(" +
      "\005\022\027\n\017sequence_number\030\004 \001(\005\022\021\n\ttimestamp\030" +
      "\005 \001(\003\022%\n\007payload\030\006 \001(\0132\024.messages.WorldM" +
      "odelB\024B\020_File_TeamPacketP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          messages._File_WorldModel.getDescriptor(),
        }, assigner);
    internal_static_messages_TeamPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_messages_TeamPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_messages_TeamPacket_descriptor,
        new java.lang.String[] { "Header", "TeamNumber", "PlayerNumber", "SequenceNumber", "Timestamp", "Payload", });
    messages._File_WorldModel.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
