// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AudioCommand.proto

package messages;

public final class AudioCommandOuterClass {
  private AudioCommandOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AudioCommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:messages.AudioCommand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string audio_file = 1;</code>
     *
     * <pre>
     *path to wav file (look at SoundPaths.h)
     * </pre>
     */
    boolean hasAudioFile();
    /**
     * <code>optional string audio_file = 1;</code>
     *
     * <pre>
     *path to wav file (look at SoundPaths.h)
     * </pre>
     */
    java.lang.String getAudioFile();
    /**
     * <code>optional string audio_file = 1;</code>
     *
     * <pre>
     *path to wav file (look at SoundPaths.h)
     * </pre>
     */
    com.google.protobuf.ByteString
        getAudioFileBytes();
  }
  /**
   * Protobuf type {@code messages.AudioCommand}
   */
  public static final class AudioCommand extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:messages.AudioCommand)
      AudioCommandOrBuilder {
    // Use AudioCommand.newBuilder() to construct.
    private AudioCommand(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AudioCommand(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AudioCommand defaultInstance;
    public static AudioCommand getDefaultInstance() {
      return defaultInstance;
    }

    public AudioCommand getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AudioCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              audioFile_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return messages.AudioCommandOuterClass.internal_static_messages_AudioCommand_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return messages.AudioCommandOuterClass.internal_static_messages_AudioCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              messages.AudioCommandOuterClass.AudioCommand.class, messages.AudioCommandOuterClass.AudioCommand.Builder.class);
    }

    public static com.google.protobuf.Parser<AudioCommand> PARSER =
        new com.google.protobuf.AbstractParser<AudioCommand>() {
      public AudioCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AudioCommand(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AudioCommand> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int AUDIO_FILE_FIELD_NUMBER = 1;
    private java.lang.Object audioFile_;
    /**
     * <code>optional string audio_file = 1;</code>
     *
     * <pre>
     *path to wav file (look at SoundPaths.h)
     * </pre>
     */
    public boolean hasAudioFile() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string audio_file = 1;</code>
     *
     * <pre>
     *path to wav file (look at SoundPaths.h)
     * </pre>
     */
    public java.lang.String getAudioFile() {
      java.lang.Object ref = audioFile_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          audioFile_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string audio_file = 1;</code>
     *
     * <pre>
     *path to wav file (look at SoundPaths.h)
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAudioFileBytes() {
      java.lang.Object ref = audioFile_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        audioFile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      audioFile_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getAudioFileBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getAudioFileBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static messages.AudioCommandOuterClass.AudioCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static messages.AudioCommandOuterClass.AudioCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static messages.AudioCommandOuterClass.AudioCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static messages.AudioCommandOuterClass.AudioCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static messages.AudioCommandOuterClass.AudioCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static messages.AudioCommandOuterClass.AudioCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static messages.AudioCommandOuterClass.AudioCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static messages.AudioCommandOuterClass.AudioCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static messages.AudioCommandOuterClass.AudioCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static messages.AudioCommandOuterClass.AudioCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(messages.AudioCommandOuterClass.AudioCommand prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code messages.AudioCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:messages.AudioCommand)
        messages.AudioCommandOuterClass.AudioCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return messages.AudioCommandOuterClass.internal_static_messages_AudioCommand_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return messages.AudioCommandOuterClass.internal_static_messages_AudioCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                messages.AudioCommandOuterClass.AudioCommand.class, messages.AudioCommandOuterClass.AudioCommand.Builder.class);
      }

      // Construct using messages.AudioCommandOuterClass.AudioCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        audioFile_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return messages.AudioCommandOuterClass.internal_static_messages_AudioCommand_descriptor;
      }

      public messages.AudioCommandOuterClass.AudioCommand getDefaultInstanceForType() {
        return messages.AudioCommandOuterClass.AudioCommand.getDefaultInstance();
      }

      public messages.AudioCommandOuterClass.AudioCommand build() {
        messages.AudioCommandOuterClass.AudioCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public messages.AudioCommandOuterClass.AudioCommand buildPartial() {
        messages.AudioCommandOuterClass.AudioCommand result = new messages.AudioCommandOuterClass.AudioCommand(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.audioFile_ = audioFile_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof messages.AudioCommandOuterClass.AudioCommand) {
          return mergeFrom((messages.AudioCommandOuterClass.AudioCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(messages.AudioCommandOuterClass.AudioCommand other) {
        if (other == messages.AudioCommandOuterClass.AudioCommand.getDefaultInstance()) return this;
        if (other.hasAudioFile()) {
          bitField0_ |= 0x00000001;
          audioFile_ = other.audioFile_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        messages.AudioCommandOuterClass.AudioCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (messages.AudioCommandOuterClass.AudioCommand) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object audioFile_ = "";
      /**
       * <code>optional string audio_file = 1;</code>
       *
       * <pre>
       *path to wav file (look at SoundPaths.h)
       * </pre>
       */
      public boolean hasAudioFile() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string audio_file = 1;</code>
       *
       * <pre>
       *path to wav file (look at SoundPaths.h)
       * </pre>
       */
      public java.lang.String getAudioFile() {
        java.lang.Object ref = audioFile_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            audioFile_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string audio_file = 1;</code>
       *
       * <pre>
       *path to wav file (look at SoundPaths.h)
       * </pre>
       */
      public com.google.protobuf.ByteString
          getAudioFileBytes() {
        java.lang.Object ref = audioFile_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          audioFile_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string audio_file = 1;</code>
       *
       * <pre>
       *path to wav file (look at SoundPaths.h)
       * </pre>
       */
      public Builder setAudioFile(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        audioFile_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string audio_file = 1;</code>
       *
       * <pre>
       *path to wav file (look at SoundPaths.h)
       * </pre>
       */
      public Builder clearAudioFile() {
        bitField0_ = (bitField0_ & ~0x00000001);
        audioFile_ = getDefaultInstance().getAudioFile();
        onChanged();
        return this;
      }
      /**
       * <code>optional string audio_file = 1;</code>
       *
       * <pre>
       *path to wav file (look at SoundPaths.h)
       * </pre>
       */
      public Builder setAudioFileBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        audioFile_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:messages.AudioCommand)
    }

    static {
      defaultInstance = new AudioCommand(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:messages.AudioCommand)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_AudioCommand_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_AudioCommand_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022AudioCommand.proto\022\010messages\"\"\n\014AudioC" +
      "ommand\022\022\n\naudio_file\030\001 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_messages_AudioCommand_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_messages_AudioCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_messages_AudioCommand_descriptor,
        new java.lang.String[] { "AudioFile", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
