// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Vision.proto

package messages;

public interface CornersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messages.Corners)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .messages.Corner corner = 1;</code>
   */
  java.util.List<messages.Corner> 
      getCornerList();
  /**
   * <code>repeated .messages.Corner corner = 1;</code>
   */
  messages.Corner getCorner(int index);
  /**
   * <code>repeated .messages.Corner corner = 1;</code>
   */
  int getCornerCount();
  /**
   * <code>repeated .messages.Corner corner = 1;</code>
   */
  java.util.List<? extends messages.CornerOrBuilder> 
      getCornerOrBuilderList();
  /**
   * <code>repeated .messages.Corner corner = 1;</code>
   */
  messages.CornerOrBuilder getCornerOrBuilder(
      int index);
}
