// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LedCommand.proto

package messages;

/**
 * Protobuf type {@code messages.LedCommand}
 */
public final class LedCommand extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:messages.LedCommand)
    LedCommandOrBuilder {
  // Use LedCommand.newBuilder() to construct.
  private LedCommand(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private LedCommand(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final LedCommand defaultInstance;
  public static LedCommand getDefaultInstance() {
    return defaultInstance;
  }

  public LedCommand getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private LedCommand(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              ledId_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000001;
            }
            ledId_.add(input.readInt32());
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
              ledId_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              ledId_.add(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          case 16: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              rgbHex_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000002;
            }
            rgbHex_.add(input.readInt32());
            break;
          }
          case 18: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
              rgbHex_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000002;
            }
            while (input.getBytesUntilLimit() > 0) {
              rgbHex_.add(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        ledId_ = java.util.Collections.unmodifiableList(ledId_);
      }
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        rgbHex_ = java.util.Collections.unmodifiableList(rgbHex_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return messages._File_LedCommand.internal_static_messages_LedCommand_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return messages._File_LedCommand.internal_static_messages_LedCommand_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            messages.LedCommand.class, messages.LedCommand.Builder.class);
  }

  public static com.google.protobuf.Parser<LedCommand> PARSER =
      new com.google.protobuf.AbstractParser<LedCommand>() {
    public LedCommand parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LedCommand(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<LedCommand> getParserForType() {
    return PARSER;
  }

  public static final int LED_ID_FIELD_NUMBER = 1;
  private java.util.List<java.lang.Integer> ledId_;
  /**
   * <code>repeated int32 led_id = 1;</code>
   *
   * <pre>
   * LED ID and hex value.
   * Both fields _must_ have an equal number of entries.
   * </pre>
   */
  public java.util.List<java.lang.Integer>
      getLedIdList() {
    return ledId_;
  }
  /**
   * <code>repeated int32 led_id = 1;</code>
   *
   * <pre>
   * LED ID and hex value.
   * Both fields _must_ have an equal number of entries.
   * </pre>
   */
  public int getLedIdCount() {
    return ledId_.size();
  }
  /**
   * <code>repeated int32 led_id = 1;</code>
   *
   * <pre>
   * LED ID and hex value.
   * Both fields _must_ have an equal number of entries.
   * </pre>
   */
  public int getLedId(int index) {
    return ledId_.get(index);
  }

  public static final int RGB_HEX_FIELD_NUMBER = 2;
  private java.util.List<java.lang.Integer> rgbHex_;
  /**
   * <code>repeated int32 rgb_hex = 2;</code>
   */
  public java.util.List<java.lang.Integer>
      getRgbHexList() {
    return rgbHex_;
  }
  /**
   * <code>repeated int32 rgb_hex = 2;</code>
   */
  public int getRgbHexCount() {
    return rgbHex_.size();
  }
  /**
   * <code>repeated int32 rgb_hex = 2;</code>
   */
  public int getRgbHex(int index) {
    return rgbHex_.get(index);
  }

  private void initFields() {
    ledId_ = java.util.Collections.emptyList();
    rgbHex_ = java.util.Collections.emptyList();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    for (int i = 0; i < ledId_.size(); i++) {
      output.writeInt32(1, ledId_.get(i));
    }
    for (int i = 0; i < rgbHex_.size(); i++) {
      output.writeInt32(2, rgbHex_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < ledId_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(ledId_.get(i));
      }
      size += dataSize;
      size += 1 * getLedIdList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < rgbHex_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(rgbHex_.get(i));
      }
      size += dataSize;
      size += 1 * getRgbHexList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static messages.LedCommand parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static messages.LedCommand parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static messages.LedCommand parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static messages.LedCommand parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static messages.LedCommand parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static messages.LedCommand parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static messages.LedCommand parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static messages.LedCommand parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static messages.LedCommand parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static messages.LedCommand parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(messages.LedCommand prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code messages.LedCommand}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:messages.LedCommand)
      messages.LedCommandOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return messages._File_LedCommand.internal_static_messages_LedCommand_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return messages._File_LedCommand.internal_static_messages_LedCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              messages.LedCommand.class, messages.LedCommand.Builder.class);
    }

    // Construct using messages.LedCommand.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      ledId_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      rgbHex_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return messages._File_LedCommand.internal_static_messages_LedCommand_descriptor;
    }

    public messages.LedCommand getDefaultInstanceForType() {
      return messages.LedCommand.getDefaultInstance();
    }

    public messages.LedCommand build() {
      messages.LedCommand result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public messages.LedCommand buildPartial() {
      messages.LedCommand result = new messages.LedCommand(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        ledId_ = java.util.Collections.unmodifiableList(ledId_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.ledId_ = ledId_;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        rgbHex_ = java.util.Collections.unmodifiableList(rgbHex_);
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.rgbHex_ = rgbHex_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof messages.LedCommand) {
        return mergeFrom((messages.LedCommand)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(messages.LedCommand other) {
      if (other == messages.LedCommand.getDefaultInstance()) return this;
      if (!other.ledId_.isEmpty()) {
        if (ledId_.isEmpty()) {
          ledId_ = other.ledId_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureLedIdIsMutable();
          ledId_.addAll(other.ledId_);
        }
        onChanged();
      }
      if (!other.rgbHex_.isEmpty()) {
        if (rgbHex_.isEmpty()) {
          rgbHex_ = other.rgbHex_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureRgbHexIsMutable();
          rgbHex_.addAll(other.rgbHex_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      messages.LedCommand parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (messages.LedCommand) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<java.lang.Integer> ledId_ = java.util.Collections.emptyList();
    private void ensureLedIdIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        ledId_ = new java.util.ArrayList<java.lang.Integer>(ledId_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int32 led_id = 1;</code>
     *
     * <pre>
     * LED ID and hex value.
     * Both fields _must_ have an equal number of entries.
     * </pre>
     */
    public java.util.List<java.lang.Integer>
        getLedIdList() {
      return java.util.Collections.unmodifiableList(ledId_);
    }
    /**
     * <code>repeated int32 led_id = 1;</code>
     *
     * <pre>
     * LED ID and hex value.
     * Both fields _must_ have an equal number of entries.
     * </pre>
     */
    public int getLedIdCount() {
      return ledId_.size();
    }
    /**
     * <code>repeated int32 led_id = 1;</code>
     *
     * <pre>
     * LED ID and hex value.
     * Both fields _must_ have an equal number of entries.
     * </pre>
     */
    public int getLedId(int index) {
      return ledId_.get(index);
    }
    /**
     * <code>repeated int32 led_id = 1;</code>
     *
     * <pre>
     * LED ID and hex value.
     * Both fields _must_ have an equal number of entries.
     * </pre>
     */
    public Builder setLedId(
        int index, int value) {
      ensureLedIdIsMutable();
      ledId_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 led_id = 1;</code>
     *
     * <pre>
     * LED ID and hex value.
     * Both fields _must_ have an equal number of entries.
     * </pre>
     */
    public Builder addLedId(int value) {
      ensureLedIdIsMutable();
      ledId_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 led_id = 1;</code>
     *
     * <pre>
     * LED ID and hex value.
     * Both fields _must_ have an equal number of entries.
     * </pre>
     */
    public Builder addAllLedId(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureLedIdIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, ledId_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 led_id = 1;</code>
     *
     * <pre>
     * LED ID and hex value.
     * Both fields _must_ have an equal number of entries.
     * </pre>
     */
    public Builder clearLedId() {
      ledId_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Integer> rgbHex_ = java.util.Collections.emptyList();
    private void ensureRgbHexIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        rgbHex_ = new java.util.ArrayList<java.lang.Integer>(rgbHex_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated int32 rgb_hex = 2;</code>
     */
    public java.util.List<java.lang.Integer>
        getRgbHexList() {
      return java.util.Collections.unmodifiableList(rgbHex_);
    }
    /**
     * <code>repeated int32 rgb_hex = 2;</code>
     */
    public int getRgbHexCount() {
      return rgbHex_.size();
    }
    /**
     * <code>repeated int32 rgb_hex = 2;</code>
     */
    public int getRgbHex(int index) {
      return rgbHex_.get(index);
    }
    /**
     * <code>repeated int32 rgb_hex = 2;</code>
     */
    public Builder setRgbHex(
        int index, int value) {
      ensureRgbHexIsMutable();
      rgbHex_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 rgb_hex = 2;</code>
     */
    public Builder addRgbHex(int value) {
      ensureRgbHexIsMutable();
      rgbHex_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 rgb_hex = 2;</code>
     */
    public Builder addAllRgbHex(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureRgbHexIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, rgbHex_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 rgb_hex = 2;</code>
     */
    public Builder clearRgbHex() {
      rgbHex_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:messages.LedCommand)
  }

  static {
    defaultInstance = new LedCommand(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:messages.LedCommand)
}

