// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VisionRobot.proto

package messages;

public interface RobotObstacleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messages.RobotObstacle)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional float closest_y = 1;</code>
   */
  boolean hasClosestY();
  /**
   * <code>optional float closest_y = 1;</code>
   */
  float getClosestY();

  /**
   * <code>optional float box_bottom = 2;</code>
   */
  boolean hasBoxBottom();
  /**
   * <code>optional float box_bottom = 2;</code>
   */
  float getBoxBottom();

  /**
   * <code>optional float box_left = 3;</code>
   */
  boolean hasBoxLeft();
  /**
   * <code>optional float box_left = 3;</code>
   */
  float getBoxLeft();

  /**
   * <code>optional float box_right = 4;</code>
   */
  boolean hasBoxRight();
  /**
   * <code>optional float box_right = 4;</code>
   */
  float getBoxRight();
}
