// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Motion.proto

package messages;

/**
 * Protobuf type {@code messages.ScriptedProvider}
 */
public  final class ScriptedProvider extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:messages.ScriptedProvider)
    ScriptedProviderOrBuilder {
  // Use ScriptedProvider.newBuilder() to construct.
  private ScriptedProvider(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ScriptedProvider() {
    active_ = false;
    stopping_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ScriptedProvider(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            active_ = input.readBool();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            stopping_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return messages._File_Motion.internal_static_messages_ScriptedProvider_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return messages._File_Motion.internal_static_messages_ScriptedProvider_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            messages.ScriptedProvider.class, messages.ScriptedProvider.Builder.class);
  }

  private int bitField0_;
  public static final int ACTIVE_FIELD_NUMBER = 1;
  private boolean active_;
  /**
   * <code>optional bool active = 1;</code>
   */
  public boolean hasActive() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional bool active = 1;</code>
   */
  public boolean getActive() {
    return active_;
  }

  public static final int STOPPING_FIELD_NUMBER = 2;
  private boolean stopping_;
  /**
   * <code>optional bool stopping = 2;</code>
   */
  public boolean hasStopping() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional bool stopping = 2;</code>
   */
  public boolean getStopping() {
    return stopping_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBool(1, active_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBool(2, stopping_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, active_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, stopping_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static messages.ScriptedProvider parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static messages.ScriptedProvider parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static messages.ScriptedProvider parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static messages.ScriptedProvider parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static messages.ScriptedProvider parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static messages.ScriptedProvider parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static messages.ScriptedProvider parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static messages.ScriptedProvider parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static messages.ScriptedProvider parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static messages.ScriptedProvider parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(messages.ScriptedProvider prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code messages.ScriptedProvider}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:messages.ScriptedProvider)
      messages.ScriptedProviderOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return messages._File_Motion.internal_static_messages_ScriptedProvider_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return messages._File_Motion.internal_static_messages_ScriptedProvider_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              messages.ScriptedProvider.class, messages.ScriptedProvider.Builder.class);
    }

    // Construct using messages.ScriptedProvider.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      active_ = false;
      bitField0_ = (bitField0_ & ~0x00000001);
      stopping_ = false;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return messages._File_Motion.internal_static_messages_ScriptedProvider_descriptor;
    }

    public messages.ScriptedProvider getDefaultInstanceForType() {
      return messages.ScriptedProvider.getDefaultInstance();
    }

    public messages.ScriptedProvider build() {
      messages.ScriptedProvider result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public messages.ScriptedProvider buildPartial() {
      messages.ScriptedProvider result = new messages.ScriptedProvider(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.active_ = active_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.stopping_ = stopping_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof messages.ScriptedProvider) {
        return mergeFrom((messages.ScriptedProvider)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(messages.ScriptedProvider other) {
      if (other == messages.ScriptedProvider.getDefaultInstance()) return this;
      if (other.hasActive()) {
        setActive(other.getActive());
      }
      if (other.hasStopping()) {
        setStopping(other.getStopping());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      messages.ScriptedProvider parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (messages.ScriptedProvider) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private boolean active_ ;
    /**
     * <code>optional bool active = 1;</code>
     */
    public boolean hasActive() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bool active = 1;</code>
     */
    public boolean getActive() {
      return active_;
    }
    /**
     * <code>optional bool active = 1;</code>
     */
    public Builder setActive(boolean value) {
      bitField0_ |= 0x00000001;
      active_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool active = 1;</code>
     */
    public Builder clearActive() {
      bitField0_ = (bitField0_ & ~0x00000001);
      active_ = false;
      onChanged();
      return this;
    }

    private boolean stopping_ ;
    /**
     * <code>optional bool stopping = 2;</code>
     */
    public boolean hasStopping() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool stopping = 2;</code>
     */
    public boolean getStopping() {
      return stopping_;
    }
    /**
     * <code>optional bool stopping = 2;</code>
     */
    public Builder setStopping(boolean value) {
      bitField0_ |= 0x00000002;
      stopping_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool stopping = 2;</code>
     */
    public Builder clearStopping() {
      bitField0_ = (bitField0_ & ~0x00000002);
      stopping_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:messages.ScriptedProvider)
  }

  // @@protoc_insertion_point(class_scope:messages.ScriptedProvider)
  private static final messages.ScriptedProvider DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new messages.ScriptedProvider();
  }

  public static messages.ScriptedProvider getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<ScriptedProvider>
      PARSER = new com.google.protobuf.AbstractParser<ScriptedProvider>() {
    public ScriptedProvider parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new ScriptedProvider(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<ScriptedProvider> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ScriptedProvider> getParserForType() {
    return PARSER;
  }

  public messages.ScriptedProvider getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

