// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BallModel.proto

package messages;

public interface VisionBallOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messages.VisionBall)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional double distance = 1;</code>
   */
  boolean hasDistance();
  /**
   * <code>optional double distance = 1;</code>
   */
  double getDistance();

  /**
   * <code>optional double bearing = 2;</code>
   */
  boolean hasBearing();
  /**
   * <code>optional double bearing = 2;</code>
   */
  double getBearing();

  /**
   * <code>optional double angle_x_deg = 3;</code>
   */
  boolean hasAngleXDeg();
  /**
   * <code>optional double angle_x_deg = 3;</code>
   */
  double getAngleXDeg();

  /**
   * <code>optional double angle_y_deg = 4;</code>
   */
  boolean hasAngleYDeg();
  /**
   * <code>optional double angle_y_deg = 4;</code>
   */
  double getAngleYDeg();

  /**
   * <code>optional double bearing_sd = 5;</code>
   */
  boolean hasBearingSd();
  /**
   * <code>optional double bearing_sd = 5;</code>
   */
  double getBearingSd();

  /**
   * <code>optional bool inTopCam = 6;</code>
   */
  boolean hasInTopCam();
  /**
   * <code>optional bool inTopCam = 6;</code>
   */
  boolean getInTopCam();

  /**
   * <code>optional double radius = 7;</code>
   */
  boolean hasRadius();
  /**
   * <code>optional double radius = 7;</code>
   */
  double getRadius();

  /**
   * <code>optional double confidence = 8;</code>
   */
  boolean hasConfidence();
  /**
   * <code>optional double confidence = 8;</code>
   */
  double getConfidence();

  /**
   * <code>optional bool on = 9;</code>
   */
  boolean hasOn();
  /**
   * <code>optional bool on = 9;</code>
   */
  boolean getOn();

  /**
   * <code>optional sint32 frames_on = 10;</code>
   */
  boolean hasFramesOn();
  /**
   * <code>optional sint32 frames_on = 10;</code>
   */
  int getFramesOn();

  /**
   * <code>optional sint32 frames_off = 11;</code>
   */
  boolean hasFramesOff();
  /**
   * <code>optional sint32 frames_off = 11;</code>
   */
  int getFramesOff();

  /**
   * <code>optional double rel_x_variance = 12;</code>
   */
  boolean hasRelXVariance();
  /**
   * <code>optional double rel_x_variance = 12;</code>
   */
  double getRelXVariance();

  /**
   * <code>optional double rel_y_variance = 13;</code>
   */
  boolean hasRelYVariance();
  /**
   * <code>optional double rel_y_variance = 13;</code>
   */
  double getRelYVariance();

  /**
   * <code>optional double bearing_deg = 14;</code>
   */
  boolean hasBearingDeg();
  /**
   * <code>optional double bearing_deg = 14;</code>
   */
  double getBearingDeg();

  /**
   * <code>optional sint32 x = 15;</code>
   */
  boolean hasX();
  /**
   * <code>optional sint32 x = 15;</code>
   */
  int getX();

  /**
   * <code>optional sint32 y = 16;</code>
   */
  boolean hasY();
  /**
   * <code>optional sint32 y = 16;</code>
   */
  int getY();
}
