
##
# Includes
##

IF( BUILDING_FOR_A_REMOTE_NAO )
  SET( ALCOMMON_INCLUDE_DIR ${OE_SYSROOT}/usr/include/ )
ENDIF()

IF( BUILDING_FOR_A_REMOTE_NAO ) 
  SET( ALCOMMON_LIBRARIES
    ${OE_SYSROOT}/usr/lib/libalcommon.so
    ${OE_SYSROOT}/usr/lib/libalmemoryfastaccess.so)
ENDIF()

IF( EXISTS "${ALCOMMON_LIBRARIES}" AND ALCOMMON_LIBRARIES )
    SET( ALCOMMON_FOUND TRUE )
ENDIF( EXISTS "${ALCOMMON_LIBRARIES}" AND ALCOMMON_LIBRARIES )

IF( NOT ALCOMMON_FOUND_TRUE AND ALCOMMON_FIND_REQUIRED )
    IF( NOT ALCOMMON_INCLUDE_DIR )
        MESSAGE( STATUS "Required include not found" )
        MESSAGE( FATAL_ERROR "Could not find ALCOMMON include!")
    ENDIF( NOT ALCOMMON_INCLUDE_DIR )
    IF( NOT ALCOMMON_LIBRARIES )
        MESSAGE( STATUS "Required libraries not found" )
        MESSAGE( FATAL_ERROR "Could not find ALCOMMON libraries!")
    ENDIF( NOT ALCOMMON_LIBRARIES )
ENDIF( NOT ALCOMMON_FOUND_TRUE AND ALCOMMON_FIND_REQUIRED )

##
# Finally, display informations if not in quiet mode
##

IF( NOT ALCOMMON_FIND_QUIETLY )
  MESSAGE( STATUS "ALCOMMON found " )
  MESSAGE( STATUS "  includes   : ${ALCOMMON_INCLUDE_DIR}" )
  MESSAGE( STATUS "  libraries  : ${ALCOMMON_LIBRARIES}" )
  MESSAGE( STATUS "  definitions: ${ALCOMMON_DEFINITIONS}" )
ENDIF( NOT ALCOMMON_FIND_QUIETLY )



MARK_AS_ADVANCED(
  ALCOMMON_DEFINITIONS
  ALCOMMON_INCLUDE_DIR
  ALCOMMON_LIBRARIES
)
