SET( AL_DIR "$ENV{AL_DIR}" )

SET( PROXIES_INCLUDE_DIR ${AL_DIR}/include/alproxies/ )
#FILE( GLOB PROXIES_FILES RELATIVE ${PROXIES_INCLUDE_DIR} ${PROXIES_INCLUDE_DIR}*proxy.h )
SET(${PROXIES_FILES} "" )

MARK_AS_ADVANCED( PROXIES_INCLUDE_DIR PROXIES_FILES )
