#!/bin/sh
PROJDIR="/srv/www/naoweb"
PIDFILE="/tmp/webal.pid"
SOCKET="/tmp/fcgi-nao.sock"
case "$1" in
  start)

    cd "$PROJDIR"
#    LD_LIBRARY_PATH=/opt/naoqi/extern/c/linux/lib ./manage.py runfcgi socket=$SOCKET pidfile=$PIDFILE method=threaded outlog=/var/log/naopathe.out errlog=/var/log/naopathe.err &
    echo "fcgi server launched in background"
    ;;

  stop)

    cd /tmp
    if [ -f $PIDFILE ]; then
      kill `cat -- $PIDFILE`
      rm -f -- $PIDFILE
    fi
    ;;

  restart)

    echo "* restarting $DESC: $NAME... "
    $0 stop
    $0 start
    echo "done."
    ;;

  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
