#!/bin/sh

# Script to sync tables between robocup and your local tables

USAGE="./sync [up-down] \nExample: $> ./sync down"

UP_OR_DOWN=$1

RSYNC=rsync
RSYNC_OPTS="-rvzcupt"
UP_OPTS="--chmod=ug+rw"

if [ "$1" = "" ]; then
    echo "No push direction specified"
    echo $USAGE
    exit 1
fi

echo "Type username for RoboCup server, followed by [ENTER]"
read username

SERVER=$username@eisbaer.local
ROBOCUP_DIR=
TABLES_DIR=/home/d-mac/tables
DEST=.
EXCLUDE_SYNC=--exclude=sync*
EXCLUDE_GIT="--exclude=tables.git* --exclude=.git*"


SYNC_UP="$RSYNC $RSYNC_OPTS $UP_OPTS $EXCLUDE_SYNC $EXCLUDE_GIT $DEST/ $SERVER:/$ROBOCUP_DIR/$TABLES_DIR/"
SYNC_DOWN="$RSYNC $RSYNC_OPTS $EXCLUDE_SYNC $EXCLUDE_GIT $SERVER:/$ROBOCUP_DIR/$TABLES_DIR/ $DEST/"
DIFF="$RSYNC $RSYNC_OPTS -n $EXCLUDE_SYNC $EXCLUDE_GIT $DEST/ $SERVER:/$ROBOCUP_DIR/$TABLES_DIR/"

CH_OWN="ssh $SERVER chgrp -R robocupgrp $ROBOCUP_DIR/$TABLES_DIR"

if [ "$UP_OR_DOWN" = "up" ]; then

    echo "Syncing FROM `pwd` TO $SERVER/$ROBOCUP_DIR/$TABLES_DIR"
    echo $SYNC_UP
    $SYNC_UP
    echo $CH_OWN
    $CH_OWN

elif [ "$UP_OR_DOWN" = "down" ]; then

    echo "Syncing FROM $SERVER/$ROBOCUP_DIR/$TABLES_DIR TO `pwd` "
    echo $SYNC_DOWN
    $SYNC_DOWN

elif [ "$UP_OR_DOWN"="diff" ]; then
    echo "Getting diff"
    echo $DIFF
    $DIFF

else
echo "Invalid parameters"
echo $USAGE
exit 1
fi