from . import BrunswickSpeeds as speeds

#TODO TODO TODO TODO!!!!!!!! clean this shit up.

#navstates.py
MAX_X_MAGNITUDE = speeds.MAX_X_MAGNITUDE
MIN_X_MAGNITUDE = speeds.MIN_X_MAGNITUDE
MAX_Y_MAGNITUDE = speeds.MAX_Y_MAGNITUDE
MIN_Y_MAGNITUDE = speeds.MIN_Y_MAGNITUDE
MAX_SPIN_MAGNITUDE = speeds.MAX_SPIN_MAGNITUDE
MIN_SPIN_MAGNITUDE = speeds.MIN_SPIN_MAGNITUDE
OMNI_MAX_X_MAGNITUDE = speeds.MAX_OMNI_X_MAGNITUDE
OMNI_MIN_X_MAGNITUDE = speeds.MIN_OMNI_X_MAGNITUDE
OMNI_MAX_Y_MAGNITUDE = speeds.MAX_OMNI_Y_MAGNITUDE
OMNI_MIN_Y_MAGNITUDE = speeds.MIN_OMNI_Y_MAGNITUDE
OMNI_MAX_SPIN_MAGNITUDE = speeds.MAX_SPIN_WHILE_X_MAGNITUDE
OMNI_MIN_SPIN_MAGNITUDE = speeds.MIN_SPIN_WHILE_X_MAGNITUDE

GOTO_FORWARD_SPEED = speeds.FWD_MAX_SPEED
GOTO_BACKWARD_SPEED = speeds.REV_MAX_SPEED
GOTO_LEFT_SPEED = speeds.LEFT_MAX_SPEED
GOTO_RIGHT_SPEED = speeds.RIGHT_MAX_SPEED
GOTO_LEFT_SPIN_SPEED = speeds.LEFT_SPIN_MAX_SPEED
GOTO_RIGHT_SPIN_SPEED = speeds.RIGHT_SPIN_MAX_SPEED
GOTO_STRAIGHT_SPIN_SPEED = speeds.MAX_SPIN_MAGNITUDE

WALK_TO_FWD_MAX_SPEED = speeds.FWD_MAX_SPEED
WALK_TO_FWD_MIN_SPEED = speeds.FWD_MIN_SPEED
WALK_TO_REV_MAX_SPEED = speeds.REV_MAX_SPEED
WALK_TO_REV_MIN_SPEED = speeds.REV_MIN_SPEED
WALK_TO_MAX_LEFT_SPIN_SPEED = speeds.LEFT_SPIN_WHILE_X_MAX_SPEED
WALK_TO_MIN_LEFT_SPIN_SPEED = speeds.LEFT_SPIN_WHILE_X_MIN_SPEED
WALK_TO_MAX_RIGHT_SPIN_SPEED = speeds.RIGHT_SPIN_WHILE_X_MAX_SPEED
WALK_TO_MIN_RIGHT_SPIN_SPEED = speeds.RIGHT_SPIN_WHILE_X_MIN_SPEED

OMNI_FWD_MAX_SPEED = speeds.OMNI_FWD_MAX_SPEED
OMNI_FWD_MIN_SPEED = speeds.OMNI_FWD_MIN_SPEED
OMNI_REV_MAX_SPEED = speeds.OMNI_REV_MAX_SPEED
OMNI_REV_MIN_SPEED = speeds.OMNI_REV_MIN_SPEED
OMNI_LEFT_MAX_SPEED = speeds.OMNI_LEFT_MAX_SPEED
OMNI_LEFT_MIN_SPEED = speeds.OMNI_LEFT_MAX_SPEED
OMNI_RIGHT_MAX_SPEED = speeds.OMNI_RIGHT_MAX_SPEED
OMNI_RIGHT_MIN_SPEED = speeds.OMNI_RIGHT_MIN_SPEED
OMNI_MAX_LEFT_SPIN_SPEED = speeds.LEFT_SPIN_WHILE_X_MAX_SPEED
OMNI_MIN_LEFT_SPIN_SPEED = speeds.LEFT_SPIN_WHILE_X_MIN_SPEED
OMNI_MAX_RIGHT_SPIN_SPEED = speeds.RIGHT_SPIN_WHILE_X_MAX_SPEED
OMNI_MIN_RIGHT_SPIN_SPEED = speeds.RIGHT_SPIN_WHILE_X_MIN_SPEED

OMNI_GOTO_FORWARD_SPEED = speeds.OMNI_FWD_MAX_SPEED
OMNI_GOTO_STRAFE_SPEED = speeds.MAX_OMNI_Y_MAGNITUDE
OMNI_GAIN = 0.7                 # Max normalized speed while omni-ing

# orbitPoint values
ORBIT_LEFT = -1               # Spin right to orbit left
ORBIT_RIGHT = 1               # Spin left to orbit right
MIN_ORBIT_ANGLE = 10

REDUCED_SPEED_DISTANCE = 10.0

KICK_POSITION_GAIN = 0.4

CLOSE_ENOUGH_X = 5.0
CLOSE_ENOUGH_Y = 5.0
CLOSE_ENOUGH_H = 10.0
CLOSE_ENOUGH = (CLOSE_ENOUGH_X, CLOSE_ENOUGH_Y, CLOSE_ENOUGH_H)

#navigator.py
LOC_IS_ACTIVE_H  = 720
CLOSE_ENOUGH_XY = 25.0
CLOSER_XY = 15.0
ALMOST_CLOSE_ENOUGH_H = 30.0

AT_HEADING_GOTO_DEG = 20

### Walk Constants
### Values used to compare walk vectors
SPIN_EPSILON = 0.1
FORWARD_EPSILON = 0.1
STRAFE_EPSILON = 0.1

### Walk Speed initialization values
### Used to initialize or reset walk vector memory
WALK_VECTOR_INIT = -1337

# Types of destinations for Navigator
NUM_DEST_TYPES = 3
(PLAYBOOK_DEST,
 GO_TO_DEST,
 BALL) = range(NUM_DEST_TYPES)

POSITION_NEAR_THRESH = CLOSER_XY
POSITION_MEDIUM_THRESH = CLOSE_ENOUGH_XY
POSITION_NEAR_SCALE = 0
POSITION_MEDIUM_SCALE = 0.6
POSITION_FAR_SCALE = 1.0

FRAME_RATE = 30       # Rough estimate of fps

MIN_SPIN_SPEED = speeds.MIN_SPIN_MAGNITUDE
MIN_SPIN_MAGNITUDE_WALK = speeds.MIN_SPIN_WHILE_X_MAGNITUDE

FINAL_HEADING_DIST = 100
FINAL_HEADING_READY_DIST = 60
HEADING_THRESHOLD_TO_SPIN = 60
FRAMES_THRESHOLD_TO_SPIN = 30
FRAMES_THRESHOLD_TO_GOTO_POSITION = FRAMES_THRESHOLD_TO_POSITION_OMNI = 15
FRAMES_THRESHOLD_TO_POSITION_PLAYBOOK = 10
FRAMES_THRESHOLD_TO_AT_POSITION = 10

# turnToBall
FIND_BALL_SPIN_SPEED = speeds.MAX_SPIN_MAGNITUDE
BALL_SPIN_SPEED = speeds.MAX_SPIN_MAGNITUDE
MIN_BALL_SPIN_MAGNITUDE = speeds.MIN_SPIN_MAGNITUDE

# approachBall() values
APPROACH_X_WITH_GAIN_DIST = 1./150.
APPROACH_Y_WITH_GAIN_DIST = 1./30.
APPROACH_THETA_WITH_GAIN_DIST = 1./90.

# Obstacle avoidance stuff
SHOULD_AVOID_OBSTACLE_APPROACH_DIST = 50.0
AVOID_OBSTACLE_FRONT_DIST = 40.0 #cm
AVOID_OBSTACLE_SIDE_DIST = 30.0 #cm
AVOID_OBSTACLE_FRAMES_THRESH = 2
DONE_AVOIDING_FRAMES_THRESH = 10
DODGE_BACK_SPEED = speeds.REV_MAX_SPEED
DODGE_RIGHT_SPEED = speeds.RIGHT_MAX_SPEED
DODGE_LEFT_SPEED = speeds.LEFT_MAX_SPEED

# conversion values for dealing with gait stuff from motion engine
TO_CMS = 0.1 #from MM/S
TO_DEGS = 57.2958
