#!/bin/bash

NBITES_FIFO="/home/nao/nbites/nbitesFIFO"

if [ $# -ne 1 ]; then
   echo "ERROR: man requires a single argument"
   echo "Usage: man [ stop | start | restart | print ]"
   exit 1
fi

if [[ $1 == "stop" ]]; then
   echo "killing"
   echo 'k' > $NBITES_FIFO
   exit 0

elif [[ $1 == "restart" ]]; then
   echo "restarting"
   echo 'r' > $NBITES_FIFO
   exit 0

elif [[ $1 == "start" ]]; then
   echo "starting"
   echo 's' > $NBITES_FIFO
   exit 0

elif [[ $1 == "print" ]]; then
   echo "printing"
   echo 'p' > $NBITES_FIFO
   exit 0

else
   echo "UNKNOWN COMMAND"
   exit 1
fi


