#!/bin/bash

BIN=$NBITES_DIR/build/nbclient

rm -rf $BIN
mkdir $BIN

find ./src -name *.java > _tempFiles
javac -d $BIN @_tempFiles

cp ./src/nbclient/util/*.properties $BIN/nbclient/util
rm _tempFiles
