#!/bin/sh

#Script to sync frames between robot and your computer
ROBOT=$1

LOCAL_DEST=$2
LOCAL_DEST=$LOCAL_DEST-$ROBOT

USAGE="./grab <robot-name> <folder-destination>\nExample: $> ./grab zaphod graz/falseBalls"

if [ "$1" = "" ]; then
    echo "No robot specified"
    echo $USAGE
    exit 1
fi

if [ "$2" = "" ]; then
    echo "No local destination specified"
    echo $USAGE
    exit 1
fi

echo "mkdir -p $LOCAL_DEST"
mkdir -p $LOCAL_DEST

# set directory to be world-writable so we can add learning files etc.

chmod a+w $LOCAL_DEST

echo "scp -r nao@$ROBOT:/home/nao/naoqi/frames/* $LOCAL_DEST/"
scp -r nao@$ROBOT:/home/nao/naoqi/frames/* $LOCAL_DEST/
