#!/bin/sh

# Script to sync frames between robocup and your local frames folder


USAGE="./sync [up-down] <folder-name> \nExample: $> ./sync down watson"

UP_OR_DOWN=$1
REMOTE_FOLDER=${2%/} #Strip the trailing slash if any

RSYNC=rsync
RSYNC_OPTS=-rvt

if [ "$1" = "" ]; then
    echo "No push direction specified"
    echo $USAGE
    exit 1
fi

if [ "$REMOTE_FOLDER" = "" ]; then
    echo "No remote folder specified"
    echo $USAGE
    exit 1
fi

echo "Type username for RoboCup server, followed by [ENTER]"
read username

SERVER=$username@robocup.bowdoin.edu:
ROBOCUP_DIR=/mnt/research/robocup
FRAMES_DIR=frames

if [ "$UP_OR_DOWN" = "up" ]; then

    echo "Syncing FROM `pwd`/$REMOTE_FOLDER TO $SERVER/$ROBOCUP_DIR/$FRAMES_DIR/$REMOTE_FOLDER"
    echo "$RSYNC $RSYNC_OPTS $REMOTE_FOLDER $SERVER/$ROBOCUP_DIR/$FRAMES_DIR"
    $RSYNC $RSYNC_OPTS $REMOTE_FOLDER $SERVER/$ROBOCUP_DIR/$FRAMES_DIR

elif [ "$UP_OR_DOWN" = "down" ]; then

    echo "Syncing FROM $SERVER/$REMOTE_FOLDER TO `pwd`/$REMOTE_FOLDER "
    echo "cd ../ && $RSYNC $RSYNC_OPTS $SERVER/$REMOTE_FOLDER ./"
    cd ../ && $RSYNC $RSYNC_OPTS $SERVER/$ROBOCUP_DIR/$FRAMES_DIR/$REMOTE_FOLDER/* ./$FRAMES_DIR/$REMOTE_FOLDER
else
echo "Invalid parameters"
echo $USAGE
exit 1
fi