MAX_X_SPEED = 7
MIN_X_SPEED = -4
MIN_X_MAGNITUDE = 1.5

MAX_Y_SPEED = 6
MIN_Y_SPEED = -MAX_Y_SPEED
MIN_Y_MAGNITUDE = 2

MAX_SPIN_SPEED = 25.0
MIN_SPIN_SPEED = -MAX_SPIN_SPEED
MIN_SPIN_MAGNITUDE = 4.0

MAX_SPIN_WHILE_X_SPEED = 10.0
MIN_SPIN_WHILE_X_SPEED = -MAX_SPIN_WHILE_X_SPEED
MIN_SPIN_WHILE_X_MAGNITUDE = 4.0
