
# Transition Constants

# Frame thresholds
FRAMES_ON_THRESH = 2
FRAMES_OFF_THRESH = 5
GIVE_UP_THRESH = 36


BALL_BEARING_THRESH = 12


# close approach/turn thresholds
BALL_CLOSE_DIST_THRESH = 38
BALL_CLOSE_BEARING_THRESH = 5

BALL_POS_KICK_DIST_THRESH = 27

BALL_KICK_DIST_THRESH = 15
BALL_KICK_BEARING_THRESH_LOWER = 15
BALL_KICK_BEARING_THRESH_UPPER = 30

SPIN_SPEED = 15
BALL_SPIN_SPEED = 8
Y_SPIN_SPEED = 1.0
X_SPEED_TO_BALL = 0
Y_SLOW_SPEED = 3

CLOSE_TURN_GAIN = 2.3
CLOSE_TURN_Y_GAIN = .6

APPROACH_X_GAIN = 6.0
APPROACH_Y_GAIN = 1.3

APPROACH_CLOSE_X_GAIN = 2.5
APPROACH_CLOSE_Y_GAIN = 2.0
