from .. import NogginConstants as Constants

BALL_SAVE_LIMIT_TIME = 2.5
MOVE_TO_SAVE_DIST_THRESH = 200.
CENTER_SAVE_THRESH = 15.
ORTHO_GOTO_THRESH = Constants.CENTER_FIELD_X * 0.5
STRAFE_ONLY = True
STRAFE_SPEED = 6
STRAFE_STEPS = 3
MAX_FRAMES_OFF_CENTER = 360
MAX_STEPS_OFF_CENTER = 50
BUFFER = 50
STRAFE_THRESH_ONE = 10
STRAFE_THRESH_TWO = 15
STRAFE_THRESH_THREE = 25
STRAFE_THRESH_FOUR = 35
STRAFE_THRESH_FIVE = 45
STRAFE_THRESH_SIX = 55
STRAFE_THESH_SEVEN = 65

AGGRESSIVENESS_OFFSET = 10
GOALBOX_Y_REDUCTION = 20
END_CLEAR_BUFFER = 10

# Distance at which we use active localization
ACTIVE_LOC_THRESH = 150.

# Difference to goto a different point
SHOULD_POSITION_DIFF = 5.0
