import BrunswickSpeeds as speeds
USE_SQUAT_DEFENDER = False

BALL_SPIN_POSITION_THRESH = 10
BALL_SPIN_BUFFER = 10
BALL_OFF_SPIN_TIME = 30

RELOC_UNCERT_XY_THRESH = 100
RELOC_UNCERT_THETA_THRESH = 40
WELL_LOCED_UNCERT_XY = 30
WELL_LOCED_UNCERT_THRESH = 25

RELOC_SPIN_FRAME_THRESH = 70
SHOULD_RELOC_FRAME_THRESH = 6

RELOC_SPIN_SPEED = speeds.MAX_SPIN_SPEED

AT_POSITION_KICK_DIST = 25
NOT_AT_POSITION_FRAMES_THRESH = 5
CHANGE_OMNI_THRESH = 0
OMNI_POSITION_DIST = 100
OMNI_POSITION_READY_DIST = 50
GOTO_DEST_EPSILON = 10.
