BALL_SPIN_POSITION_THRESH = 10
BALL_SPIN_BUFFER = 10
AT_POSITION_KICK_DIST = 25
BALL_OFF_SPIN_TIME = 30

RELOC_UNCERT_XY_THRESH = 50
RELOC_UNCERT_THETA_THRESH = 30
WELL_LOCED_UNCERT_XY = 20
WELL_LOCED_UNCERT_THRESH = 15

RELOC_SPIN_FRAME_THRESH = 70

RELOC_SPIN_SPEED = 25
