BALL_SPIN_POSITION_THRESH = 10
BALL_SPIN_BUFFER = 10
BALL_OFF_SPIN_TIME = 30

RELOC_UNCERT_XY_THRESH = 100
RELOC_UNCERT_THETA_THRESH = 40
WELL_LOCED_UNCERT_XY = 30
WELL_LOCED_UNCERT_THRESH = 25

RELOC_SPIN_FRAME_THRESH = 70

RELOC_SPIN_SPEED = 25

AT_POSITION_KICK_DIST = 25
NOT_AT_POSITION_FRAMES_THRESH = 5
