#!/bin/bash

BIN=$NBITES_DIR/build/nbtool

rm -rf $BIN
#might need to make build dir too on some systems
mkdir $BIN

find ./src -name *.java > _tempFiles
javac -d $BIN @_tempFiles

cp ./src/nbtool/util/*.properties $BIN/nbtool/util
rm _tempFiles
