#!/bin/bash

echo "RUNnbtool (no build)"

BIN_BASE=$NBITES_DIR/build/java/

BIN_LIBS=$BIN_BASE/libs/
BIN_NBTOOL=$BIN_BASE/volatile/

LIB_APACHE=$BIN_LIBS/apache/
LIB_BHUMAN=$BIN_LIBS/bhuman/
LIB_GOOGLE=$BIN_LIBS/google/

JARS_EXTERNAL=$NBITES_DIR/src/nbtool/jars-external/

cd $BIN_NBTOOL
java -ea -Xms200m -Xmx200m -cp .:$JARS_EXTERNAL:$LIB_GOOGLE:$LIB_BHUMAN:$LIB_APACHE nbtool.term.NBTool_v7
