#!/bin/bash

NBITES_FIFO="/home/nao/nbites/nbitesFIFO"

if [ $# -ne 1 ]; then
   echo "ERROR: man requires a single argument"
   echo "Usage: man [stop | start | restart | done]"
   exit 1
fi

if [[ $1 == "kill" ]]; then
   echo 'k' > $NBITES_FIFO

elif [[ $1 == "restart" ]]; then
   echo 'r' > $NBITES_FIFO
   # Deleting the nblog so that it only contains this instance of mans output
   rm /home/nao/nbites/log/nblog
   naolog

elif [[ $1 == "start" ]]; then
   echo 's' > $NBITES_FIFO
   # Deleting the nblog so that it only contains this instance of mans output
   rm /home/nao/nbites/log/nblog
   naolog

elif [[ $1 == "done" ]]; then
   done
fi
