#!/bin/sh

MAL=192.168.16.102
JAYNE=192.168.16.103
RIVER=192.168.16.104
WASH=192.168.16.105
ZOE=192.168.16.106
ROBOT=""

HOST=$MAL
ROBOT="mal"
nmap -sP -T1 $HOST 2>&1 | grep "Host is up"
if [ "$?" -eq 0 ]; then
    echo "$ROBOT is up at $HOST."
else
    echo "ERROR: $HOST unreachable, $ROBOT is down!"
fi
echo "\n"

HOST=$JAYNE
ROBOT="jayne"
nmap -sP -T1 $HOST 2>&1 | grep "Host is up"
if [ "$?" -eq 0 ]; then
    echo "$ROBOT is up at $HOST."
else
    echo "ERROR: $HOST unreachable, $ROBOT is down!"
fi
echo "\n"

HOST=$RIVER
ROBOT="river"
nmap -sP -T1 $HOST 2>&1 | grep "Host is up"
if [ "$?" -eq 0 ]; then
    echo "$ROBOT is up at $HOST."
else
    echo "ERROR: $HOST unreachable, $ROBOT is down!"
fi
echo "\n"

HOST=$WASH
ROBOT="wash"
nmap -sP -T1 $HOST 2>&1 | grep "Host is up"
if [ "$?" -eq 0 ]; then
    echo "$ROBOT is up at $HOST."
else
    echo "ERROR: $HOST unreachable, $ROBOT is down!"
fi
echo "\n"

HOST=$ZOE
ROBOT="zoe"
nmap -sP -T1 $HOST 2>&1 | grep "Host is up"
if [ "$?" -eq 0 ]; then
    echo "$ROBOT is up at $HOST."
else
    echo "ERROR: $HOST unreachable, $ROBOT is down!"
fi