#!/bin/bash
# Get mounted partition names and new desired hostname
# Since the "/home/nao" and the "/" are different partitions, we must ask for both.
if [ $# -ne 2 ] ; then
    echo "Bad number of arguments"
    echo "usage: setup-usb-key usb_root_partition hostname"
    exit 1
fi

if [ x$(whoami) != xroot ]; then
    echo "setup-usb-key must be run as root."
    echo "Be very careful and give it the right paths."
    exit 1
fi

ROOT_PART=$1
HOSTNAME=$2

CONFIG_DIR=../config

LIB_DIR=../../lib
# Add libboost_python-mt.so
cp $LIB_DIR/nao/libboost_python-mt.so $ROOT_PART/usr/lib/
cp $LIB_DIR/nao/libprotobuf.so $ROOT_PART/usr/lib/
cp $LIB_DIR/nao/lxv4l2.ko $ROOT_PART/lib/modules/2.6.29.6-rt24-aldebaran-rt/kernel/drivers/media/video/lxv4l2/

# Change hostname
echo $HOSTNAME > $ROOT_PART/etc/hostname

# Set up init
cp  -r $CONFIG_DIR/etc $ROOT_PART/
