
##
# Includes
##

INCLUDE( ${CMAKE_MODULE_PATH}/base_definitions.cmake )

##
# Clear variables/caches
##

SET( PYTHON_DEFINITIONS "" )
SET( PYTHON_INCLUDE_DIR "PYTHON_INCLUDE_DIR-NOTFOUND" CACHE FILEPATH "Cleared." FORCE)
SET( PYTHON_LIBRARIES "PYTHON_LIBRARIES-NOTFOUND" CACHE FILEPATH "Cleared." FORCE)


##
# Defined package variable
##

IF( WIN32 )
  SET( PYTHON_INCLUDE_DIR $ENV{PYTHON_PATH}/Include)
  SET( PYTHON_LIBRARIES $ENV{PYTHON_PATH}/Lib/python25.lib)
ELSE( WIN32 )
  IF( OE_CROSS_BUILD )
    IF( ROBOT_AIBO )
      SET( PYTHON_INCLUDE_DIR "${OE_CROSS_DIR}/pythonlib/include/python2.5" )
      SET( PYTHON_LIBRARIES "${OE_CROSS_DIR}/pythonlib/libpython2.5.a" )
    ELSE( ROBOT_AIBO )
      SET( PYTHON_INCLUDE_DIR ${INCLUDE_PREFIX}/python2.5 )
      SET( PYTHON_LIBRARIES ${LIB_PREFIX}/libpython2.5.so )
    ENDIF( ROBOT_AIBO )
  ELSE( OE_CROSS_BUILD )
    SET( PYTHON_INCLUDE_DIR /usr/include/python2.5 )
    IF ( APPLE )
      SET( PYTHON_LIBRARIES /usr/lib/libpython2.5.dylib )
    ELSE ( APPLE )
      SET( PYTHON_LIBRARIES /usr/lib/libpython2.5.so )
    ENDIF( APPLE )
  ENDIF( OE_CROSS_BUILD )
ENDIF( WIN32 )



IF( PYTHON_INCLUDE_DIR AND PYTHON_LIBRARIES )
  IF ( EXISTS PYTHON_INCLUDE_DIR AND EXISTS PYTHON_LIBRARIES )
    SET( PYTHON_FOUND TRUE )
  ENDIF ( EXISTS PYTHON_INCLUDE_DIR AND EXISTS PYTHON_LIBRARIES )
ENDIF( PYTHON_INCLUDE_DIR AND PYTHON_LIBRARIES )

IF( NOT PYTHON_FOUND AND PYTHON_FIND_REQUIRED )
  IF( NOT PYTHON_INCLUDE_DIR OR NOT EXISTS ${PYTHON_INCLUDE_DIR} )
    MESSAGE( STATUS "Required include not found" )
    MESSAGE( FATAL_ERROR "Could not find PYTHON include!" )
  ENDIF( NOT PYTHON_INCLUDE_DIR OR NOT EXISTS ${PYTHON_INCLUDE_DIR} )
  IF( NOT PYTHON_LIBRARIES OR NOT EXISTS ${PYTHON_LIBRARIES} )
    MESSAGE( STATUS "Required libraries not found" )
    MESSAGE( FATAL_ERROR "Could not find PYTHON libraries!" )
  ENDIF( NOT PYTHON_LIBRARIES OR NOT EXISTS ${PYTHON_LIBRARIES} )
ENDIF( NOT PYTHON_FOUND AND PYTHON_FIND_REQUIRED )

# Finally, display informations if not in quiet mode
IF( NOT PYTHON_FIND_QUIETLY )
  MESSAGE( STATUS "PYTHON found " )
  MESSAGE( STATUS "  includes   : ${PYTHON_INCLUDE_DIR}" )
  MESSAGE( STATUS "  libraries  : ${PYTHON_LIBRARIES}" )
  MESSAGE( STATUS "  definitions: ${PYTHON_DEFINITIONS}" )
ENDIF( NOT PYTHON_FIND_QUIETLY )



MARK_AS_ADVANCED(
  PYTHON_DEFINITIONS
  PYTHON_INCLUDE_DIR
  PYTHON_LIBRARIES
)
