// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VisionRobot.proto

package messages;

public final class _File_VisionRobot {
  private _File_VisionRobot() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_VisionRobot_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_VisionRobot_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_Robot_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_Robot_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_VisionObstacle_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_VisionObstacle_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_RobotObstacle_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_RobotObstacle_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021VisionRobot.proto\022\010messages\"\310\002\n\013Vision" +
      "Robot\022\035\n\004red1\030\001 \001(\0132\017.messages.Robot\022\035\n\004" +
      "red2\030\002 \001(\0132\017.messages.Robot\022\035\n\004red3\030\003 \001(" +
      "\0132\017.messages.Robot\022\035\n\004red4\030\004 \001(\0132\017.messa" +
      "ges.Robot\022\035\n\004red5\030\005 \001(\0132\017.messages.Robot" +
      "\022\036\n\005navy1\030\006 \001(\0132\017.messages.Robot\022\036\n\005navy" +
      "2\030\007 \001(\0132\017.messages.Robot\022\036\n\005navy3\030\010 \001(\0132" +
      "\017.messages.Robot\022\036\n\005navy4\030\t \001(\0132\017.messag" +
      "es.Robot\022\036\n\005navy5\030\n \001(\0132\017.messages.Robot" +
      "\"\301\001\n\005Robot\022\020\n\010distance\030\001 \001(\002\022\017\n\007bearing\030",
      "\002 \001(\002\022\023\n\013bearing_deg\030\003 \001(\002\022\023\n\013angle_x_de" +
      "g\030\004 \001(\002\022\023\n\013angle_y_deg\030\005 \001(\002\022\t\n\001x\030\006 \001(\021\022" +
      "\t\n\001y\030\007 \001(\021\022\025\n\relevation_deg\030\010 \001(\002\022\n\n\002on\030" +
      "\t \001(\010\022\016\n\006height\030\n \001(\021\022\r\n\005width\030\013 \001(\021\"\375\001\n" +
      "\016VisionObstacle\022\017\n\007on_left\030\001 \001(\010\022\020\n\010on_r" +
      "ight\030\002 \001(\010\022\021\n\toff_field\030\003 \001(\010\022\022\n\nblock_l" +
      "eft\030\004 \001(\021\022\021\n\tblock_mid\030\005 \001(\021\022\023\n\013block_ri" +
      "ght\030\006 \001(\021\022\021\n\tleft_dist\030\007 \001(\002\022\020\n\010mid_dist" +
      "\030\010 \001(\002\022\022\n\nright_dist\030\t \001(\002\022\024\n\014left_beari" +
      "ng\030\n \001(\002\022\023\n\013mid_bearing\030\013 \001(\002\022\025\n\rright_b",
      "earing\030\014 \001(\002\"[\n\rRobotObstacle\022\021\n\tclosest" +
      "_y\030\001 \001(\002\022\022\n\nbox_bottom\030\002 \001(\002\022\020\n\010box_left" +
      "\030\003 \001(\002\022\021\n\tbox_right\030\004 \001(\002B\025B\021_File_Visio" +
      "nRobotP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_messages_VisionRobot_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_messages_VisionRobot_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messages_VisionRobot_descriptor,
              new java.lang.String[] { "Red1", "Red2", "Red3", "Red4", "Red5", "Navy1", "Navy2", "Navy3", "Navy4", "Navy5", });
          internal_static_messages_Robot_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_messages_Robot_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messages_Robot_descriptor,
              new java.lang.String[] { "Distance", "Bearing", "BearingDeg", "AngleXDeg", "AngleYDeg", "X", "Y", "ElevationDeg", "On", "Height", "Width", });
          internal_static_messages_VisionObstacle_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_messages_VisionObstacle_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messages_VisionObstacle_descriptor,
              new java.lang.String[] { "OnLeft", "OnRight", "OffField", "BlockLeft", "BlockMid", "BlockRight", "LeftDist", "MidDist", "RightDist", "LeftBearing", "MidBearing", "RightBearing", });
          internal_static_messages_RobotObstacle_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_messages_RobotObstacle_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messages_RobotObstacle_descriptor,
              new java.lang.String[] { "ClosestY", "BoxBottom", "BoxLeft", "BoxRight", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
