// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FSR.proto

package messages;

public final class _File_FSR {
  private _File_FSR() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_FSR_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_FSR_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tFSR.proto\022\010messages\"m\n\003FSR\022\013\n\003lfl\030\001 \001(" +
      "\002\022\013\n\003lfr\030\002 \001(\002\022\013\n\003lrl\030\003 \001(\002\022\013\n\003lrr\030\004 \001(\002" +
      "\022\013\n\003rfl\030\005 \001(\002\022\013\n\003rfr\030\006 \001(\002\022\013\n\003rrl\030\007 \001(\002\022" +
      "\013\n\003rrr\030\010 \001(\002B\rB\t_File_FSRP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_messages_FSR_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_messages_FSR_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_messages_FSR_descriptor,
        new java.lang.String[] { "Lfl", "Lfr", "Lrl", "Lrr", "Rfl", "Rfr", "Rrl", "Rrr", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
