// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AudioCommand.proto

package messages;

public interface AudioCommandOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional string audio_file = 1;
  /**
   * <code>optional string audio_file = 1;</code>
   *
   * <pre>
   *path to wav file (look at SoundPaths.h)
   * </pre>
   */
  boolean hasAudioFile();
  /**
   * <code>optional string audio_file = 1;</code>
   *
   * <pre>
   *path to wav file (look at SoundPaths.h)
   * </pre>
   */
  java.lang.String getAudioFile();
  /**
   * <code>optional string audio_file = 1;</code>
   *
   * <pre>
   *path to wav file (look at SoundPaths.h)
   * </pre>
   */
  com.google.protobuf.ByteString
      getAudioFileBytes();
}
