// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PMotion.proto

package messages;

public interface BodyJointCommandOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional float time = 1;
  /**
   * <code>optional float time = 1;</code>
   */
  boolean hasTime();
  /**
   * <code>optional float time = 1;</code>
   */
  float getTime();

  // optional .messages.JointAngles angles = 2;
  /**
   * <code>optional .messages.JointAngles angles = 2;</code>
   */
  boolean hasAngles();
  /**
   * <code>optional .messages.JointAngles angles = 2;</code>
   */
  messages.JointAngles getAngles();
  /**
   * <code>optional .messages.JointAngles angles = 2;</code>
   */
  messages.JointAnglesOrBuilder getAnglesOrBuilder();

  // optional .messages.JointAngles stiffness = 3;
  /**
   * <code>optional .messages.JointAngles stiffness = 3;</code>
   */
  boolean hasStiffness();
  /**
   * <code>optional .messages.JointAngles stiffness = 3;</code>
   */
  messages.JointAngles getStiffness();
  /**
   * <code>optional .messages.JointAngles stiffness = 3;</code>
   */
  messages.JointAnglesOrBuilder getStiffnessOrBuilder();

  // optional .messages.BodyJointCommand.InterpolationType interpolation = 4;
  /**
   * <code>optional .messages.BodyJointCommand.InterpolationType interpolation = 4;</code>
   */
  boolean hasInterpolation();
  /**
   * <code>optional .messages.BodyJointCommand.InterpolationType interpolation = 4;</code>
   */
  messages.BodyJointCommand.InterpolationType getInterpolation();
}
