// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FeetOnGround.proto

package messages;

public interface FeetOnGroundOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional bool on_ground = 1;
  /**
   * <code>optional bool on_ground = 1;</code>
   */
  boolean hasOnGround();
  /**
   * <code>optional bool on_ground = 1;</code>
   */
  boolean getOnGround();
}
