// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ButtonState.proto

package messages;

public interface FootBumperStateOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional .messages.ButtonState l_foot_bumper_left = 1;
  /**
   * <code>optional .messages.ButtonState l_foot_bumper_left = 1;</code>
   *
   * <pre>
   * Left foot bumpers.
   * </pre>
   */
  boolean hasLFootBumperLeft();
  /**
   * <code>optional .messages.ButtonState l_foot_bumper_left = 1;</code>
   *
   * <pre>
   * Left foot bumpers.
   * </pre>
   */
  messages.ButtonState getLFootBumperLeft();
  /**
   * <code>optional .messages.ButtonState l_foot_bumper_left = 1;</code>
   *
   * <pre>
   * Left foot bumpers.
   * </pre>
   */
  messages.ButtonStateOrBuilder getLFootBumperLeftOrBuilder();

  // optional .messages.ButtonState l_foot_bumper_right = 2;
  /**
   * <code>optional .messages.ButtonState l_foot_bumper_right = 2;</code>
   */
  boolean hasLFootBumperRight();
  /**
   * <code>optional .messages.ButtonState l_foot_bumper_right = 2;</code>
   */
  messages.ButtonState getLFootBumperRight();
  /**
   * <code>optional .messages.ButtonState l_foot_bumper_right = 2;</code>
   */
  messages.ButtonStateOrBuilder getLFootBumperRightOrBuilder();

  // optional .messages.ButtonState r_foot_bumper_left = 3;
  /**
   * <code>optional .messages.ButtonState r_foot_bumper_left = 3;</code>
   *
   * <pre>
   * Right foot bumpers.
   * </pre>
   */
  boolean hasRFootBumperLeft();
  /**
   * <code>optional .messages.ButtonState r_foot_bumper_left = 3;</code>
   *
   * <pre>
   * Right foot bumpers.
   * </pre>
   */
  messages.ButtonState getRFootBumperLeft();
  /**
   * <code>optional .messages.ButtonState r_foot_bumper_left = 3;</code>
   *
   * <pre>
   * Right foot bumpers.
   * </pre>
   */
  messages.ButtonStateOrBuilder getRFootBumperLeftOrBuilder();

  // optional .messages.ButtonState r_foot_bumper_right = 4;
  /**
   * <code>optional .messages.ButtonState r_foot_bumper_right = 4;</code>
   */
  boolean hasRFootBumperRight();
  /**
   * <code>optional .messages.ButtonState r_foot_bumper_right = 4;</code>
   */
  messages.ButtonState getRFootBumperRight();
  /**
   * <code>optional .messages.ButtonState r_foot_bumper_right = 4;</code>
   */
  messages.ButtonStateOrBuilder getRFootBumperRightOrBuilder();
}
