// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ParticleSwarm.proto

package messages;

public interface ParticleOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional float weight = 1;
  /**
   * <code>optional float weight = 1;</code>
   */
  boolean hasWeight();
  /**
   * <code>optional float weight = 1;</code>
   */
  float getWeight();

  // optional .messages.RobotLocation loc = 2;
  /**
   * <code>optional .messages.RobotLocation loc = 2;</code>
   */
  boolean hasLoc();
  /**
   * <code>optional .messages.RobotLocation loc = 2;</code>
   */
  messages.RobotLocation getLoc();
  /**
   * <code>optional .messages.RobotLocation loc = 2;</code>
   */
  messages.RobotLocationOrBuilder getLocOrBuilder();
}
