// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ParticleSwarm.proto

package messages;

public interface ParticleSwarmOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // repeated .messages.Particle particle = 1;
  /**
   * <code>repeated .messages.Particle particle = 1;</code>
   */
  java.util.List<messages.Particle> 
      getParticleList();
  /**
   * <code>repeated .messages.Particle particle = 1;</code>
   */
  messages.Particle getParticle(int index);
  /**
   * <code>repeated .messages.Particle particle = 1;</code>
   */
  int getParticleCount();
  /**
   * <code>repeated .messages.Particle particle = 1;</code>
   */
  java.util.List<? extends messages.ParticleOrBuilder> 
      getParticleOrBuilderList();
  /**
   * <code>repeated .messages.Particle particle = 1;</code>
   */
  messages.ParticleOrBuilder getParticleOrBuilder(
      int index);
}
