// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SonarState.proto

package messages;

public interface SonarStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messages.SonarState)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional float us_left = 1;</code>
   */
  boolean hasUsLeft();
  /**
   * <code>optional float us_left = 1;</code>
   */
  float getUsLeft();

  /**
   * <code>optional float us_right = 2;</code>
   */
  boolean hasUsRight();
  /**
   * <code>optional float us_right = 2;</code>
   */
  float getUsRight();
}
