// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Motion.proto

package messages;

public interface WalkProviderOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional bool active = 1;
  /**
   * <code>optional bool active = 1;</code>
   */
  boolean hasActive();
  /**
   * <code>optional bool active = 1;</code>
   */
  boolean getActive();

  // optional bool is_walking = 2;
  /**
   * <code>optional bool is_walking = 2;</code>
   */
  boolean hasIsWalking();
  /**
   * <code>optional bool is_walking = 2;</code>
   */
  boolean getIsWalking();

  // optional bool stopping = 3;
  /**
   * <code>optional bool stopping = 3;</code>
   */
  boolean hasStopping();
  /**
   * <code>optional bool stopping = 3;</code>
   */
  boolean getStopping();

  // optional bool requested_to_stop = 4;
  /**
   * <code>optional bool requested_to_stop = 4;</code>
   */
  boolean hasRequestedToStop();
  /**
   * <code>optional bool requested_to_stop = 4;</code>
   */
  boolean getRequestedToStop();

  // optional bool is_standing = 5;
  /**
   * <code>optional bool is_standing = 5;</code>
   */
  boolean hasIsStanding();
  /**
   * <code>optional bool is_standing = 5;</code>
   */
  boolean getIsStanding();

  // optional bool calibrated = 6;
  /**
   * <code>optional bool calibrated = 6;</code>
   */
  boolean hasCalibrated();
  /**
   * <code>optional bool calibrated = 6;</code>
   */
  boolean getCalibrated();

  // optional int32 command_type = 8;
  /**
   * <code>optional int32 command_type = 8;</code>
   */
  boolean hasCommandType();
  /**
   * <code>optional int32 command_type = 8;</code>
   */
  int getCommandType();

  // optional .messages.WalkProvider.BHDebug bhdebug = 7;
  /**
   * <code>optional .messages.WalkProvider.BHDebug bhdebug = 7;</code>
   */
  boolean hasBhdebug();
  /**
   * <code>optional .messages.WalkProvider.BHDebug bhdebug = 7;</code>
   */
  messages.WalkProvider.BHDebug getBhdebug();
  /**
   * <code>optional .messages.WalkProvider.BHDebug bhdebug = 7;</code>
   */
  messages.WalkProvider.BHDebugOrBuilder getBhdebugOrBuilder();
}
