#!/bin/sh

# Adapted for Gait PSO pickle files


USAGE="./sync [up-down] <folder-name> \nExample: $> ./sync down watson"

UP_OR_DOWN=$1
REMOTE_FOLDER=${2%/} #Strip the trailing slash if any

RSYNC=rsync
RSYNC_OPTS=-rvz

if [ "$1" = "" ]; then
    echo "No push direction specified"
    echo $USAGE
    exit 1
fi

# if [ "$REMOTE_FOLDER" = "" ]; then
#     echo "No remote folder specified"
#     echo $USAGE
#     exit 1
# fi

echo "Type username for RoboCup server, followed by [ENTER]"
read username

SERVER=$username@robocup.bowdoin.edu:
ROBOCUP_DIR=/mnt/research/robocup
GAITS_DIR=gait-pso/

SYNC_UP="$RSYNC $RSYNC_OPTS $REMOTE_FOLDER $SERVER/$ROBOCUP_DIR/$GAITS_DIR"

SYNC_DOWN="$RSYNC $RSYNC_OPTS ${SERVER}${ROBOCUP_DIR}/$GAITS_DIR/$REMOTE_FOLDER/* ./$GAITS_DIR/$REMOTE_FOLDER"

if [ "$UP_OR_DOWN" = "up" ]; then

    echo "Syncing FROM `pwd`/$REMOTE_FOLDER TO $SERVER/$ROBOCUP_DIR/$GAITS_DIR/$REMOTE_FOLDER"
    echo $SYNC_UP
    $SYNC_UP

elif [ "$UP_OR_DOWN" = "down" ]; then

    echo "Syncing FROM $SERVER/$ROBOCUP_DIR/$GAITS_DIR/$REMOTE_FOLDER TO `pwd`/$REMOTE_FOLDER "
    echo $SYNC_DOWN
    cd ../
    $SYNC_DOWN

elif [ "$UP_OR_DOWN"="diff" ]; then
    echo "Getting diff"
    RSYNC_OPTS=${RSYNC_OPTS}n
    echo $SYNC_UP
    $SYNC_UP
else
    echo "Invalid parameters"
    echo $USAGE
    exit 1
fi